address: null
development_framework:
  framework: foundry
  script: null
info:
  author: SunWeb3Sec
  description: On Oct-11-2022, Carrot on BSC was attacked via public functionCall.
  license: UNLICENSED
  references:
  - https://twitter.com/BlockSecTeam/status/1579908411235237888
  - https://bscscan.com/tx/0xa624660c29ee97f3f4ebd36232d8199e7c97533c9db711fa4027994aa11e01b9
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Carrot_exp.sol
  root_cause: public function call, call transferowner 0xbf699b4b. All wallets granted approvals are impacted.
  tags:
    chains:
    - BSC
    exploits: 
    - Abuse approvals
    project: 
    - Yield
    vulnerabilities:
    - CWE-284
    - Arbitrary call
networks:
  block_number: '22055611'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: 0.8.10
options: null
