info:
  description: On Nov-29-2022, token MBC was hacked and the attacker gained around 5.6k BUSD. The root cause is that the MBC contract use function addLiquidity() wrong and also it accidentally exposed the interface as public.
  license: 'UNLICENSED'
  author: ['zhouxianyuan', 'Kayaba-Attribution']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/MBC_exp.sol'
    - 'https://twitter.com/AnciliaInc/status/1597742575623888896'
    - 'https://twitter.com/CertiKAlert/status/1597639717096460288'
    - 'https://phalcon.blocksec.com/tx/bsc/0xdc53a6b5bf8e2962cf0e0eada6451f10956f4c0845a3ce134ddb050365f15c86'
  tags: 
    chains: ['bsc']
    project: ['token']  
    vulnerabilities: ['business logic flaw', 'access control'] #wip: CWE here
    exploits: ['flashloan', 'price oracle manipulation']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '23474460'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
- PancakeSwap/IERC20.sol
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
- PancakeSwap/IPancakePair.sol
address:
options: