address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - zhouxianyuan
  - Kayaba-Attribution
  description: On Nov-29-2022, token MBC was hacked and the attacker gained around
    5.6k BUSD. The root cause is that the MBC contract use function addLiquidity()
    wrong and also it accidentally exposed the interface as public.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/MBC_exp.sol
  - https://twitter.com/AnciliaInc/status/1597742575623888896
  - https://twitter.com/CertiKAlert/status/1597639717096460288
  - https://phalcon.blocksec.com/tx/bsc/0xdc53a6b5bf8e2962cf0e0eada6451f10956f4c0845a3ce134ddb050365f15c86
  root_cause: Use function addLiquidity() wrong and public interface
  tags:
    chains:
    - BSC
    exploits:
    - Flashloan
    - Price manipulation
    project:
    - ERC20
    vulnerabilities:
    - Business logic issue
    - CWE-284
networks:
  block_number: '23474460'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: ^0.8.10
options: null
