address: null
development_framework:
  framework: foundry
  script: null
info:
  author: SunWeb3Sec
  description: On Oct-11-2022, TempleDao was attacked and lost $2.3 million. The root
    cause is the insufficient access control to the migrateStake function.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Templedao_exp.sol
  - https://twitter.com/BlockSecTeam/status/1579843881893769222
  - https://etherscan.io/tx/0x8c3f442fc6d640a6ff3ea0b12be64f1d4609ea94edd2966f42c01cd9bdcf04b5
  root_cause: Insufficient access control to the migrateStake function
  tags:
    chains:
    - ETH
    exploits: null
    project:
    - Yield
    vulnerabilities:
    - CWE-284
networks:
  block_number: '15725066'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: 0.8.10
options: null
