address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - zzzuhaibmohd
  - SunWeb3Sec
  - finn79426
  description: On Mar-9-2022 at 01:50:20 PM +UTC, Fantasm Finance collateral reserve
    pool was exploited for ~$2.62M. The attacker was able to mint more XFTM tokens
    than anticipated and swapped all of the tokens to ETH sing privacy protocol Tornado
    Cash.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Fantasm_exp.sol
  - https://twitter.com/fantasm_finance/status/1501569232881995785
  - https://medium.com/quillhash/fantom-based-protocol-fantasm-suffers-2-6m-exploit-32de8191ccd4
  - https://www.certik.com/resources/blog/5p92144WQ44Ytm1AL4Jt9X-fantasm-finance
  root_cause: Incorrect calculation due to wrong decimal
  tags:
    chains:
    - Fantom
    exploits: null
    project:
    - Synthetic Assets
    vulnerabilities:
    - CWE-682
networks:
  block_number: '32971742'
  is_forking: '1'
  node: fantom
  private_key: null
  solidity_version: 0.8.10
options: null
