info:
  description: On Mar-9-2022 at 01:50:20 PM +UTC, Fantasm Finance collateral reserve pool was exploited for ~$2.62M. The attacker was able to mint more XFTM tokens than anticipated and swapped all of the tokens to ETH sing privacy protocol Tornado Cash.
  license: 'UNLICENSED'
  author: ['zzzuhaibmohd', 'SunWeb3Sec', 'finn79426']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Fantasm_exp.sol'
    - 'https://twitter.com/fantasm_finance/status/1501569232881995785'
    - 'https://medium.com/quillhash/fantom-based-protocol-fantasm-suffers-2-6m-exploit-32de8191ccd4'
    - 'https://www.certik.com/resources/blog/5p92144WQ44Ytm1AL4Jt9X-fantasm-finance'
  tags: 
    chains: ['fantom']
    project: ['defi']  #wip
    vulnerabilities: ['business logic issue'] #wip: incorrect error checking code 
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '32971742'
  is_forking: '1'
  private_key: ''
  solidity_version: '0.8.10'
interfaces:
address:
options: