info:
  description: On Nov-10-2022, DFXFinance was attacked for ~$4M due to the lack of proper reentrancy protection. The key of the vulnerability lies in the combination of the flashloan business and other business of the contract.
  license: 'UNLICENSED'
  author: ['zhouxianyuan']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/DFX_exp.sol'
    - 'https://twitter.com/BlockSecTeam/status/1590960299246780417'
    - 'https://twitter.com/BeosinAlert/status/1591012525914861570'
    - 'https://twitter.com/AnciliaInc/status/1590839104731684865'
    - 'https://twitter.com/peckshield/status/1590831589004816384'
  tags: 
    chains: ['ethereum']
    project: ['dex']  
    vulnerabilities: ['reentrancy'] #wip: CWE here
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '15941703'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
- Uniswap/IUniswapV2Router01.sol
- Uniswap/IUniswapV2Router02.sol
address:
options: