info:
  description: On Sep-06-2022, an attacker manipulate the price of ZOOM in the PancakeSwap by flashloan and gained around 61,160 BSC-USD. 
  license: 'UNLICENSED'
  author: ['SunWeb3Sec']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/ZoomproFinance_exp.sol'
    - 'https://twitter.com/blocksecteam/status/1567027459207606273'
    - 'https://bscscan.com/tx/0xe176bd9cfefd40dc03508e91d856bd1fe72ffc1e9260cd63502db68962b4de1a'
  tags: 
    chains: ['bsc']
    project: ['token']  
    vulnerabilities: [] #wip: CWE here
    exploits: ['flashloan', 'price manipulation']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '21055930'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
- PancakeSwap/IPancakePair.sol
address:
options: