info:
  description: On Oct-12-2022, ATK on BSC was attacked, the hackers abused Flashloan to attack the reward distribution function.
  license: 
  author: 'unknown'
  references:
    - 'url'
    - 'cve'
  tags: 
    chains: ['bsc']
    project: [] #wip  
    vulnerabilities: [] #wip: CWE here
    exploits: ['flashloan']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '22102838'
  is_forking: '1'
  private_key: ''
  solidity_version: 0.8.10
interfaces:
- PancakeSwap/IPancakeRouter02.sol
- PancakeSwap/IPancakePair.sol
address:
options: