address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - Kayaba-Attribution
  description: On Nov-22-2022, a suspicious tx gained over 49BNB (~$13K) from AURofficial_
    pancakeswap AUR/WBNB pool. Due to the lack of permission check on the function
    call changeRewardPerNode(), attacker could change that value to a huge number
    which will be used to calculate node rewards.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/AUR_exp.sol
  - https://twitter.com/AnciliaInc/status/1595142246570958848
  tags:
    chains:
    - bsc
    exploits: []
    project:
    - token
    vulnerabilities:
    - access control
    - CWE-732
networks:
  block_number: '23282134'
  is_forking: '1'
  node: bsc
  private_key: ''
  solidity_version: ^0.8.10
options: null
