address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - Kayaba-Attribution
  description: On Nov-22-2022, a suspicious tx gained over 49BNB (~$13K) from AURofficial_
    pancakeswap AUR/WBNB pool. Due to the lack of permission check on the function
    call changeRewardPerNode(), attacker could change that value to a huge number
    which will be used to calculate node rewards.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/AUR_exp.sol
  - https://twitter.com/AnciliaInc/status/1595142246570958848
  root_cause: Lack of permission check on the function call changeRewardPerNode()
  tags:
    chains:
    - BSC
    exploits: null
    project:
    - ERC20
    vulnerabilities:
    - CWE-284
    - CWE-732
networks:
  block_number: '23282134'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: ^0.8.10
options: null
