info:
  description: On Nov-22-2022, a suspicious tx gained over 49BNB (~$13K) from AURofficial_ pancakeswap AUR/WBNB pool. Due to the lack of permission check on the function call changeRewardPerNode(), attacker could change that value to a huge number which will be used to calculate node rewards.
  license: 'UNLICENSED'
  author: ['Kayaba-Attribution']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/AUR_exp.sol'
    - 'https://twitter.com/AnciliaInc/status/1595142246570958848'
  tags: 
    chains: ['bsc']
    project: ['token']  
    vulnerabilities: ['access control', 'CWE-732'] #wip: CWE here
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '23282134'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
address:
options: