address: null
development_framework:
  framework: foundry
  script: null
info:
  author: HyungSeok Han
  description: On Oct-09-2022, an attacker mint 100,000,00,000,000 $RNBW and transfer
    ownership to the attacker.
  license: UNLICENSED
  references:
  - https://twitter.com/BeosinAlert/status/1579040051853303808
  - https://etherscan.io/tx/0xc18ec2eb7d41638d9982281e766945d0428aaeda6211b4ccb6626ea7cff31f4a
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/XaveFinance_exp.sol
  root_cause: Gnosis Safe DAOModule compromised
  tags:
    chains:
    - ETH
    exploits: 
    - Malicious proposal
    project:
    - Governance
    vulnerabilities:
    - CWE-284
networks:
  block_number: '15704745'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: 0.8.10
options: null
