info:
  description: On Apr-12-2022, ElephantStatus was hacked and the official loss from this exploit is 27,416 BNB, valued at $11.2M. The attack is a traditional price manipulation attack 
  license: 'UNLICENSED'
  author: ['finn79426', 'SunWeb3Sec']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Elephant_Money_poc.sol'
    - 'https://medium.com/elephant-money/reserve-exploit-52fd36ccc7e8'
    - 'https://twitter.com/peckshield/status/1514023036596330496'
    - 'https://twitter.com/BlockSecTeam/status/1513966074357698563'
    - 'https://bscscan.com/tx/0xec317deb2f3efdc1dbf7ed5d3902cdf2c33ae512151646383a8cf8cbcd3d4577'
  tags: 
    chains: ['bsc']
    project: ['token']  #wip
    vulnerabilities: [] #wip: CWE here
    exploits: ['flashloan', 'price oracle manipulation']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '16886438'
  is_forking: '1'
  private_key: ''
  solidity_version: '0.8.10'
interfaces:
- PancakeSwap/IERC20.sol
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
- PancakeSwap/IPancakePair.sol
- IWBNB.sol
address:
options: