address:
  pair: '0x02b0551B656509754285eeC81eE894338E14C5DD'
  router: '0x10ED43C718714eb63d5aA57B78B54704E256024E'
  vulnerableToken: '0xF40d33DE6737367A1cCB0cE6a056698D993A17E1'
  wbnb: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c'
development_framework:
  framework: foundry
  script: attack.ts
info:
  author:
  - zhouxianyuan
  description: On Sep-06-2022, an attacker manipulate the price of BURG in the PancakeSwap
    and gained ~77K worth of asset. The attack was caused by a smart contract vulnerability
    that allows the token to burn in any account.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/NXUSD_exp.sol
  - https://medium.com/nereus-protocol/post-mortem-flash-loan-exploit-in-single-nxusd-market-343fa32f0c6
  - https://snowtrace.io/tx/0x0ab12913f9232b27b0664cd2d50e482ad6aa896aeb811b53081712f42d54c026
  tags:
    chains:
    - avalanche
    exploits:
    - flashloan
    project:
    - token
    - staking
    vulnerabilities: []
networks:
  block_number: '14433982'
  is_forking: '1'
  node: avalanche
  private_key: ''
  solidity_version: 0.8.4
options:
  burn_amount: '19999'
  number_of_burn_operations: '11'
  number_of_swap_operations: '4'
  swap_amount: '19999'
