info:
  description: On Jul-10-2022, OMNI Protocol was the victim of a flash loan attack. The root cause of this incident is that the burn function calls the OnERC721Received function externally, which caused the reentrancy problems.
  license: 'UNLICENSED'
  author: ['SunWeb3Sec', 'finn79426']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Omni_exp.sol'
    - 'https://twitter.com/SlowMist_Team/status/1546379086792388609'
    - 'https://etherscan.io/tx/0x05d65e0adddc5d9ccfe6cd65be4a7899ebcb6e5ec7a39787971bcc3d6ba73996'
  tags: 
    chains: ['eth']
    project: ['nft']  
    vulnerabilities: ['reentrancy'] #wip: CWE here
    exploits: ['flashloan']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '15114361'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
- Uniswap/IUniswapV2Router01.sol
- Uniswap/IUniswapV2Router02.sol
address:
options: