address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - SunWeb3Sec
  - finn79426
  description: On Jul-10-2022, OMNI Protocol was the victim of a flash loan attack.
    The root cause of this incident is that the burn function calls the OnERC721Received
    function externally, which caused the reentrancy problems.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Omni_exp.sol
  - https://twitter.com/SlowMist_Team/status/1546379086792388609
  - https://etherscan.io/tx/0x05d65e0adddc5d9ccfe6cd65be4a7899ebcb6e5ec7a39787971bcc3d6ba73996
  root_cause: safeTransferFrom in burn function. project without nonReentrant protection.
  tags:
    chains:
    - ETH
    exploits:
    - Flashloan
    project:
    - NFT
    - ERC721
    vulnerabilities:
    - Reentrancy
    - CWE-841
networks:
  block_number: '15114361'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: ^0.8.10
options: null
