address:
  alltoken: '0x04C0f31C0f59496cf195d2d7F1dA908152722DE7'
  allusdtpair: '0x1B214e38C5e861c56e12a69b6BAA0B45eFe5C8Eb'
  pancakeRouter: '0x10ED43C718714eb63d5aA57B78B54704E256024E'
  restoken: '0xecCD8B08Ac3B587B7175D40Fb9C60a20990F8D21'
  usdt: '0x55d398326f99059fF775485246999027B3197955'
  usdtrespair: '0x05ba2c512788bd95cd6D61D3109c53a14b01c82A'
  usdtwbnbpair: '0x16b9a82891338f9bA80E2D6970FddA79D1eb0daE'
development_framework:
  framework: foundry
  script: null
info:
  author: funnbee
  description: On Oct-06-2022, The attacker used a flashloan to hack The BUSD_RES
    token pair contract and gained over $290K and extra $ALL tokens.
  license: MIT
  references:
  - https://twitter.com/AnciliaInc/status/1578119778446680064
  - https://bscscan.com/tx/0xe59fa48212c4ee716c03e648e04f0ca390f4a4fc921a890fded0e01afa4ba96d
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/RES_exp.sol
  root_cause: thisAToB(), burn RES token to increase exchange ratio
  tags:
    chains:
    - BSC
    exploits:
    - Flashloan
    - Price manipulate
    project:
    - ERC20
    vulnerabilities: 
    - Business logic issue
networks:
  block_number: '21948016'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: 0.8.10
options: null
