address: null
development_framework:
  framework: foundry
  script: ''
info:
  author: zhouxianyuan
  description: On Oct-17-2022, $PLTD suffers a price manipulation attack with a profit
    of 24,497 $BUSD for the hacker.
  license: MIT
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/PLTD_exp.sol
  - https://twitter.com/BeosinAlert/status/1582181583343484928
  tags:
    chains:
    - bsc
    exploits:
    - price oracle manipulation
    project:
    - token
    vulnerabilities: []
networks:
  block_number: '22252045'
  is_forking: '1'
  node: bsc
  private_key: ''
  solidity_version: 0.8.10
options: null
