info:
  description: On Oct-24-2022, contract 0x940cE652A51EBadB5dF09d605dBEDA95fDcF697b lost $600 due to Arbitrary External Call Vulnerability. 
  license: 'UNLICENSED'
  author: ['zhouxianyuan']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/MulticallWithoutCheck_exp.sol'
  tags: 
    chains: ['polygon']
    project: ['multicall']
    vulnerabilities: ['access control', 'CWE-284'] # Arbitrary External Call Vulnerability
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '34743770'
  is_forking: '1'
  private_key: ''
  solidity_version: ^0.8.10
interfaces: []
address: []
options: []