address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - SunWeb3Sec
  description: On Aug-24-2022, LuckeyTiger NFT was hacked due to bad randomness that
    can be predicted for infinite minting.
  license: GPL-3.0
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/LuckyTiger_exp.sol
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/script/LuckyTiger_s_exp.sol
  - https://twitter.com/1nf0s3cpt/status/1576117129589317633
  - https://etherscan.io/tx/0x804ff3801542bff435a5d733f4d8a93a535d73d0de0f843fd979756a7eab26af
  - https://github.com/0xNezha/luckyHack
  tags:
    chains:
    - ethereum
    exploits: []
    project:
    - nft
    vulnerabilities:
    - bad randomness
networks:
  block_number: '15403430'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: ^0.8.13
options: null
