address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - finn79426
  description: On May-08-2022 at 08:34:42 PM +UTC, Fortress Protocol suffered a price
    oracle manipulation attack and a DAO manipulation attack with the loss of approximately
    ~$3M (1,048.1 ETH and 400,000 DAI). The `submit` function of the Chain oracle
    can be called by anyone and doesn't have a power verification.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/FortressLoans.exp.sol
  - https://twitter.com/BlockSecTeam/status/1523530484877209600
  - https://www.certik.com/resources/blog/k6eZOpnK5Kdde7RfHBZgw-fortress-loans-exploit
  tags:
    chains:
    - bsc
    exploits:
    - price oracle manipulation
    project:
    - token
    - lending
    vulnerabilities:
    - access control
networks:
  block_number: '17570125'
  is_forking: '1'
  node: bsc
  private_key: ''
  solidity_version: ^0.8.10
options: null
