info:
  description: On Oct-25-2022, n00dleSwap has an ERC777-based reentrancy issue and is being attacked, causing a loss of $29K. 
  license: 'UNLICENSED'
  author: ['zhouxianyuan']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/N00d_exp.sol'
    - 'https://twitter.com/BlockSecTeam/status/1584959295829180416'
    - 'https://twitter.com/AnciliaInc/status/1584955717877784576'
  tags: 
    chains: ['eth']
    project: ['token']  
    vulnerabilities: ['re-entrancy', 'CWE-841'] #wip: CWE here
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '15826379'
  is_forking: '1'
  private_key: ''
  solidity_version: 0.8.10
interfaces:
- Uniswap/UniswapV2Pair.sol
address:
options: