address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - SunWeb3Sec
  description: On Jan-28-2022, the Sandbox publicly announced the migration of LAND
    smart contracts due to a discovered vulnerability. An attacker could have used
    this exploit to burn a significant amount of land in the Sandbox.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Sandbox_exp.sol
  - https://slowmist.medium.com/the-vulnerability-behind-the-sandbox-land-migration-2abf68933170
  - https://etherscan.io/tx/0x34516ee081c221d8576939f68aee71e002dd5557180d45194209d6692241f7b1
  root_cause: Incorrect access control
  tags:
    chains:
    - ETH
    exploits: null
    project:
    - Metaverse
    vulnerabilities:
    - CWE-284
networks:
  block_number: '14163041'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: '>=0.7.0 <0.9.0'
options: null
