info:
  description: On Apr-08-2022, Starstream Finance had their treasury drained in an exploit and around $4M were stolen. The root cause of this exploit is the StarstreamTreasury contract's owner DistributorTreasury contract has a public execute function, which has a low-level call. The hacker can thus use this function to generate withdraw messages and withdraw STARS from StarstreamTreasury.   
  license: 'UNLICENSED'
  author: ['Rivaill']
  references:
    - 'https://github.com/Rivaill/CryptoVulhub/tree/master/StarstreamFinance20220408'
    - 'https://coincodecap.com/starstream-finance-hacked-around-4m-stolen'
  tags: 
    chains: ['metis andromeda']
    project: ['defi'] # lending, borrowing, swapping  
    vulnerabilities: ['access control'] #wip: CWE here
    exploits: []  
development_framework:
  script: 'attack.ts'
  framework: 'hardhat'
networks:
  block_number: '2205883'
  is_forking: '1'
  private_key: ''
  solidity_version: 0.8.4
interfaces:
address:
options: