info:
  description: On Aug-01-2022, Reaper Farm was hacked for ~$1.7M. As the owner address in _withdraw is controllable and without any access control, an attacker can withdraw any user's assets by calling withdraw or redeem functions. 
  license: 'UNLICENSED'
  author: ['finn79426']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/ReaperFarm.exp.sol'
    - 'https://twitter.com/Reaper_Farm/status/1554500909740302337'
    - 'https://twitter.com/BeosinAlert/status/1554476940593340421'
  tags: 
    chains: ['fantom']
    project: ['farming']  
    vulnerabilities: ['access control'] #wip: CWE here
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '44045899'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
address:
options: