address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - finn79426
  - SunWeb3Sec
  description: On Jul-01-2022, Quixotic_io was exploited and lost $100k. In the fillSellOrder
    function of the market contract, only the sell order is checked, but the buyer's
    buy order is not checked.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Quixotic_exp.sol
  - https://twitter.com/1nf0s3cpt/status/1542808565349777408
  - https://twitter.com/SlowMist_Team/status/1542795627603857409
  - https://optimistic.etherscan.io/tx/0x5dc519726e1236eb846271f6699e03cdd1a8fd593a2900c71cd2aabbdb7c92e6
  root_cause: fillSellOrder function only check seller signature
  tags:
    chains:
    - Optimism
    exploits: null
    project:
    - NFTMarketplace
    vulnerabilities:
    - CWE-20
networks:
  block_number: '13591383'
  is_forking: '1'
  node: optimism
  private_key: null
  solidity_version: 0.8.10
options: null
