info:
  description: On Oct-17-2022, Uerii Token was hacked and lost $2.4 k due to the public mint function. 
  license: 'UNLICENSED'
  author: 'zhouxianyuan'
  references:
    - 'https://twitter.com/peckshield/status/1581988895142526976'
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Uerii_exp.sol'
  tags: 
    chains: ['ethereum']
    project: ['token']  
    vulnerabilities: ['access control'] #wip: CWE here
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '15767837'
  is_forking: '1'
  private_key: ''
  solidity_version: 0.8.10
interfaces:
address:
options: