info:
  description: On Jul-25-2022, LPC was under a flashloan attack. Since the ledger balance is not updated in the _transfer function, but is modified directly on the original recipientBalance, resulting in an increase in the attacker balance.
  license: 'UNLICENSED'
  author: ['finn79426']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/LPC.exp.sol'
    - 'https://www.panewslab.com/zh_hk/articledetails/uwv4sma2.html'
    - 'https://twitter.com/BeosinAlert/status/1551535854681718784'
  tags: 
    chains: ['bsc']
    project: ['token']  
    vulnerabilities: ['logic issue', 'incorrect check'] #wip: CWE here
    exploits: ['flashloan']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '19852596'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
- PancakeSwap/IPancakePair.sol
address:
options: