address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - eugenioclrc
  - SunWeb3Sec
  description: On Oct-21-2022, the related @OlympusDAO's BondFixedExpiryTeller contract
    has a redeem() function that does not properly validate the input, resulting in
    ~$292K loss.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/OlympusDao.exp.sol
  - https://twitter.com/peckshield/status/1583416829237526528
  root_cause: Insufficient validation
  tags:
    chains:
    - ETH
    exploits: null
    project:
    - DAO
    vulnerabilities:
    - Insufficient validation
    - CWE-20
networks:
  block_number: '15794363'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: 0.8.10
options: null
