address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - zhouxianyuan
  description: On Oct-25-2022, n00dleSwap has an ERC777-based reentrancy issue and
    is being attacked, causing a loss of $29K.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/N00d_exp.sol
  - https://twitter.com/BlockSecTeam/status/1584959295829180416
  - https://twitter.com/AnciliaInc/status/1584955717877784576
  tags:
    chains:
    - ethereum
    exploits: []
    project:
    - token
    vulnerabilities:
    - re-entrancy
    - CWE-841
networks:
  block_number: '15826379'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: 0.8.10
options: null
