info:
  description: On Nov-07-2022, a flashloan attack happened on MooCakeCTX contract. The loss is ~$140K. There is no time restrictions on collateral and rewards, and the prevention of caller is not comprehensive enough, enabling the attacker to increase dividends via flashloan.
  license: 'UNLICENSED'
  author: ['zhouxianyuan']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/MooCAKECTX_exp.sol'
    - 'https://twitter.com/BeosinAlert/status/1589501207181393920'
    - 'https://twitter.com/CertiKAlert/status/1589428153591615488'
  tags: 
    chains: ['bsc']
    project: ['token', 'staking']  
    vulnerabilities: ['CWE-20'] #wip: CWE here
    exploits: ['flashloan']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '22832427'
  is_forking: '1'
  private_key: ''
  solidity_version: '0.8.10'
interfaces:
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
address:
options: