address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - finn79426
  - SunWeb3Sec
  description: On Jul-05-2022, FlippazOne NFT was hacked. The vulnerability is at
    function ownerWithdrawAllTo() which sends all the ETH in the contract to an address
    the caller can specify. The author forgot to a check to ensure only the owner
    of the contract can call this, which exists on other functions.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/FlippazOne.sol
  - https://twitter.com/bertcmiller/status/1544496577338826752
  - https://etherscan.io/tx/0x8bded20c1db5a1d5f595b15e682a95ce11d3c895d6031147fa49c4ffa5729a30
  tags:
    chains:
    - ethereum
    exploits: []
    project:
    - nft
    vulnerabilities:
    - access control
networks:
  block_number: '15083765'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: '>=0.7.0 <0.9.0'
options: null
