info:
  description: On Sep-08-2022, NewFreeDao was hacked by flashloan attack and lost 4,481 BNB (~125M US$). 
  license: 'UNLICENSED'
  author: ['finn79426']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/NewFreeDAO_exp.sol'
    - 'https://twitter.com/SlowMist_Team/status/1567854876633309186'
    - 'https://bscscan.com/tx/0x1fea385acf7ff046d928d4041db017e1d7ead66727ce7aacb3296b9d485d4a26'
  tags: 
    chains: ['bsc']
    project: ['dao']  
    vulnerabilities: ['logic issue'] #wip: CWE here
    exploits: ['flashloan']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '21140434'
  is_forking: '1'
  private_key: ''
  solidity_version: ^0.8.10
interfaces:
address:
options: