info:
  description: On Aug-09-2022, XSTABLE.PROTOCOL was attacked and the locc is around 27.13 WETH due to a logic vulnerability. 
  license: 'UNLICENSED'
  author: ['zhouxianyuan']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/XST.exp.sol'
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/XST02_exp.sol'
    - 'https://mobile.twitter.com/BlockSecTeam/status/1557195012042936320'
  tags: 
    chains: ['ethereum']
    project: ['token']  
    vulnerabilities: ['incorrect logic check'] #wip: CWE here
    exploits: ['flashloan']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '15310016'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.13'
interfaces:
- Uniswap/IUniswapV2Router01.sol
- Uniswap/IUniswapV2Router02.sol
address:
options: