address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - zhouxianyuan
  description: On Aug-09-2022, XSTABLE.PROTOCOL was attacked and the locc is around
    27.13 WETH due to a logic vulnerability.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/XST.exp.sol
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/XST02_exp.sol
  - https://mobile.twitter.com/BlockSecTeam/status/1557195012042936320
  root_cause: Incorrect Logic Check, get rewards over skim()
  tags:
    chains:
    - ETH
    exploits:
    - Flashloan
    - Price manipulation
    project:
    - Stablecoin
    - Reward
    vulnerabilities:
    - Business logic issue
networks:
  block_number: '15310016'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: ^0.8.13
options: null
