info:
  description: On Dec-21-2022, the Visor Finance was exploited and the hacker gained more than 133 ETH (~$500,000). The vulnerability is caused by arbitrary external call.
  license: 'MIT'
  author: ['Rivaill']
  references:
    - 'https://github.com/Rivaill/CryptoVulhub/tree/master/VisorFinance20211221'
    - 'https://twitter.com/VisorFinance/status/1473306777131405314'
    - 'https://www.tofreedom.me/visorfinance-re-hack'
  tags: 
    chains: ['ethereum']
    project: ['token', 'staking']  
    vulnerabilities: ['reentrancy', 'arbitrary external call'] #wip: CWE here
    exploits: []  
development_framework:
  script: 'attack.ts'
  framework: 'hardhat'
networks:
  block_number: '13849006'
  is_forking: '1'
  private_key: ''
  solidity_version: '0.8.4'
interfaces:
address:
options: