address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - SunWeb3Sec
  - 0xDatapunk
  description: On Mar-20-2022 at 02:51 AM +UTC, an attacker exploited LI.FI's smart
    contract, specifically the swapping feature which allows them to perform swaps
    before bridging, and the attacker managed to steal around $600k (current value
    $587,500 or 205 ETH) from 29 wallets.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/LiFi_exp.sol
  - https://blog.li.fi/20th-march-the-exploit-e9e1c5c03eb9
  - https://twitter.com/lifiprotocol/status/1505738407938387971
  - https://etherscan.io/tx/0x4b4143cbe7f5475029cf23d6dcbb56856366d91794426f2e33819b9b1aac4e96
  tags:
    chains:
    - ethereum
    exploits: []
    project:
    - bridge
    vulnerabilities:
    - logic issue
networks:
  block_number: '14420686'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: 0.8.10
options: null
