info:
  description: On Jul-14-2022, the SpaceGodzilla project on BSC Chain has been hit by a flash loan attack. Hackers use flash loans to borrow large amounts of funds to manipulate the price of platform coins in the PancakeSwap trading pool, and exploited the vulnerabilities in the project to attack. This attack hacker arbitrage 25,378.78BUSD. 
  license: 'UNLICENSED'
  author: ['finn79426']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/SpaceGodzilla.exp.sol'
    - 'https://mobile.twitter.com/BlockSecTeam/status/1547456591900749824'
    - 'https://medium.com/numen-cyber-labs/spacegodzilla-attack-event-analysis-d29a061b17e1'
    - 'https://learnblockchain.cn/article/4396'
  tags: 
    chains: ['bsc']
    project: ['token']  
    vulnerabilities: ['access control', 'cwe-767'] #wip: swapAndLiquifyStepv1 should be internal
    exploits: ['flashloan', 'price manipulation']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '19523980'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
- PancakeSwap/IPancakePair.sol
address:
options: