address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - zhouxianyuan
  description: On Nov-07-2022, a flashloan attack happened on MooCakeCTX contract.
    The loss is ~$140K. There is no time restrictions on collateral and rewards, and
    the prevention of caller is not comprehensive enough, enabling the attacker to
    increase dividends via flashloan.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/MooCAKECTX_exp.sol
  - https://twitter.com/BeosinAlert/status/1589501207181393920
  - https://twitter.com/CertiKAlert/status/1589428153591615488
  tags:
    chains:
    - bsc
    exploits:
    - flashloan
    project:
    - token
    - staking
    vulnerabilities:
    - CWE-20
networks:
  block_number: '22832427'
  is_forking: '1'
  node: bsc
  private_key: ''
  solidity_version: 0.8.10
options: null
