address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - finn79426
  - 0xDatapunk
  description: On Jul-23-2022, the Audius governance, staking, and delegation contracts
    on Ethereum mainnet were compromised due to a bug in the contract initialization
    code that allowed repeated invocations of the initialize functions. The bug allowed
    an attacker to maliciously transfer 18MM $AUDIO tokens held by the Audius governance
    contract (referred to as the "community treasury") to a wallet of their control
    and modify dynamics of the voting system to illicitly change their staked $AUDIO
    amounts in the network.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Audius.exp.sol
  - https://twitter.com/AudiusProject/status/1551000725169180672
  - https://twitter.com/1nf0s3cpt/status/1551050841146400768
  - https://blog.audius.co/article/audius-governance-takeover-post-mortem-7-23-22
  root_cause: Storage Collision & Malicious Proposal
  tags:
    chains:
    - ETH
    exploits:
    - Malicious proposal
    project:
    - ERC20
    - Governance
    vulnerabilities:
    - Storage collision
networks:
  block_number: '15201793'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: ^0.8.10
options: null
