address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - finn79426
  - SunWeb3Sec
  description: On Apr-10-2022, Gymdefi's LiquidityMigrationV2 contract was exploited
    for about 1,327 WBNB. The attack mainly exploits a token swap design vulnerability
    in the LiquidityMigrationV2 contract.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Gym_1_exp.sol
  - https://twitter.com/BlockSecTeam/status/1512832398643265537
  - https://medium.com/@Beosin_com/beosin-analysis-of-the-attack-on-gymdefi-e5a23bfd93fe
  - https://bscscan.com/tx/0xa5b0246f2f8d238bb56c0ddb500b04bbe0c30db650e06a41e00b6a0fff11a7e5
  tags:
    chains:
    - bsc
    exploits:
    - flashloan
    project:
    - token
    - staking
    vulnerabilities:
    - design issue
networks:
  block_number: '16798806'
  is_forking: '1'
  node: bsc
  private_key: ''
  solidity_version: 0.8.10
options: null
