address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - zhouxianyuan
  description: On Oct-01-2022, the BabySwap was attacked. The root cause is that the "factory" parameter of the router can be faked. Thus a fake swap can earn the BABY rewards token.  
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/BabySwap_exp.sol
  - https://twitter.com/BlockSecTeam/status/1576441612812836865
  - https://bscscan.com/tx/0xcca7ea9d48e00e7e32e5d005b57ec3cac28bc3ad0181e4ca208832e62aa52efe
  root_cause: Insufficient validation on the parameter
  tags:
    chains:
    - BSC
    exploits: null
    project:
    - DEX
    vulnerabilities:
    - CWE-20
networks:
  block_number: '21811979'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: '0.8.10'
options: null
