address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - zhouxianyuan
  description: On Nov-01-2022, ShadowFi suffered an exploit possibly due to a vulnerability
    of SDF token which allows the token can be burnt by anybody, the exploiter grabbed
    ~1,078 $BNB (~$301k). $SDF has dropped 98.5%.
  license: MIT
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Shadowfi_exp.sol
  - https://twitter.com/PeckShieldAlert/status/1565549688509861888
  - https://bscscan.com/tx/0xe30dc75253eecec3377e03c532aa41bae1c26909bc8618f21fb83d4330a01018
  root_cause: Public access of burn() method
  tags:
    chains:
    - BSC
    exploits:
    - Price manipulation
    project:
    - ERC20
    vulnerabilities:
    - CWE-284
networks:
  block_number: '20969095'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: ^0.8.10
options: null
