address:
  first_address: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' 
  second_address: '0x0000000000000000000000000000000000000000'
development_framework:
  framework: foundry
  script: null
info:
  author: 'author'
  description: 'The description for this exploit/PoC'
  license: 'The licneses for code'
  references: 'The references for this exploit/PoC'
  root_cause: 'The root cause for this exploit/PoC'
  tags:
    chains:
    - The blockchain related to this exploit
    exploits:
    - The type of attack/exploit toward this vulnerability
    project:
    - The type of vulnerable project/contract
    vulnerabilities:
    - CWE
    - Customized category
networks:
  # The block number need to be forked for this exploit
  block_number: '14433982'
  # Does this exploit need to fork a achive node?
  is_forking: '1'
  # The node to be forked or attack
  node: bsc
  # The private key
  private_key: null
  # The version of solidity
  solidity_version: 0.8.4
options:
  first_option: '0'
  second_option: '0'
