address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - zzzuhaibmohd
  description: On Jan-17-2022, Bad Guys project was hacked. The exploit was due to
    the missing check for "chosenAmount" in the WhiteListMint function which allowed
    the attacker to pass the number of NFTs he/she wanted to mint.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/BadGuysbyRPF_exp.sol
  - https://twitter.com/RugDoctorApe/status/1565739119606890498
  - https://etherscan.io/tx/0x27e64a8215ae1528245c912bcca09883fdd7cce69249bd5d5d1c0eecf5297b96
  root_cause: Missing check for "chosenAmount" in the WhiteListMint function
  tags:
    chains:
    - ETH
    exploits: null
    project:
    - NFT
    vulnerabilities:
    - CWE-20
networks:
  block_number: '15460093'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: 0.8.10
options: null
