address:
  pair: '0x02b0551B656509754285eeC81eE894338E14C5DD'
  router: '0x10ED43C718714eb63d5aA57B78B54704E256024E'
  vulnerableToken: '0xF40d33DE6737367A1cCB0cE6a056698D993A17E1'
  wbnb: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c'
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - zzzuhaibmohd
  description: On Jan-17-2022, Bad Guys project was hacked. The exploit was due to
    the missing check for "chosenAmount" in the WhiteListMint function which allowed
    the attacker to pass the number of NFTs he/she wanted to mint.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/BadGuysbyRPF_exp.sol
  - https://twitter.com/RugDoctorApe/status/1565739119606890498
  - https://etherscan.io/tx/0x27e64a8215ae1528245c912bcca09883fdd7cce69249bd5d5d1c0eecf5297b96
  tags:
    chains:
    - ethereum
    exploits: []
    project:
    - nft
    vulnerabilities:
    - CWE-20
networks:
  block_number: '15460093'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: 0.8.10
options:
  burn_amount: '19999'
  number_of_burn_operations: '11'
  number_of_swap_operations: '4'
  swap_amount: '19999'
