info:
  description: On Jun-05-2022, an attacker stole 20 million $OP owned by Wintermute. The root cause is the 20 million $OP on Optimism (L2) was transferred to an address that is owned by Wintermute on Ethereum (L1), but “not yet” owned by anyone on Optimism (L2).
  license: 'UNLICENSED'
  author: ['SunWeb3Sec', 'finn79426']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Optimism_exp.sol'
    - 'https://inspexco.medium.com/how-20-million-op-was-stolen-from-the-multisig-wallet-not-yet-owned-by-wintermute-3f6c75db740a'
    - 'https://optimistic.etherscan.io/tx/0x75a42f240d229518979199f56cd7c82e4fc1f1a20ad9a4864c635354b4a34261'
    - 'https://optimistic.etherscan.io/tx/0x00a3da68f0f6a69cb067f09c3f7e741a01636cbc27a84c603b468f65271d415b'
  tags: 
    chains: ['optimism']
    project: []  #WIP
    vulnerabilities: [] #wip
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '10607735'
  is_forking: '1'
  private_key: ''
  solidity_version: '0.8.10'
interfaces:
address:
options: