info:
  description: On Jun-18-2022, Schnoodle was hacked resulting in the entire liquidity in the UniswapV2Pair token being drained (104 ETH). 
  license: 'UNLICENSED'
  author: ['finn79426', 'SunWeb3Sec', 'eugenioclrc']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Snood_poc.t.sol'
    - 'https://ethereum.stackexchange.com/questions/130472/attack-on-erc-777-smart-contract-and-uniswapv2pair-resulting-in-104-eth-liquidit'
    - 'https://etherscan.io/tx/0x9a6227ef97d7ce75732645bd604ef128bb5dfbc1bfbe0966ad1cd2870d45a20e'
    - 'https://ethtx.info/mainnet/0x9a6227ef97d7ce75732645bd604ef128bb5dfbc1bfbe0966ad1cd2870d45a20e/'
  tags: 
    chains: ['ethereum']
    project: ['token']  
    vulnerabilities: ['miscalculation'] #wip: CWE here
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '14983660'
  is_forking: '1'
  private_key: ''
  solidity_version: '0.8.10'
interfaces:
- Uniswap/IUniswapV2Pair.sol
address:
options: