address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - finn79426
  - SunWeb3Sec
  description: On Jun-26-2022, XCarnival was exploited and the hacker gained of 3,087ETH
    (~$3.8M). The hack is made possible by allowing a withdrawn pledged NFT to be
    still used as the collateral, which is then exploited by the hacker to drain assets
    from the pool.
  license: UNLICENSED
  references:
  - url
  - cve
  tags:
    chains:
    - ethereum
    exploits: []
    project:
    - token
    vulnerabilities:
    - logic issue
    - no input validation
networks:
  block_number: '15028846'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: ^0.8.10
options: null
