address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - finn79426
  - SunWeb3Sec
  description: On Jun-26-2022, XCarnival was exploited and the hacker gained of 3,087ETH
    (~$3.8M). The hack is made possible by allowing a withdrawn pledged NFT to be
    still used as the collateral, which is then exploited by the hacker to drain assets
    from the pool.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/XCarnival.exp.sol
  - https://twitter.com/XCarnival_Lab/status/1541226298399653888
  - https://twitter.com/peckshield/status/1541047171453034501
  - https://twitter.com/BlockSecTeam/status/1541070850505723905
  root_cause: Call XToken contract's borrow(), there is no judgment that the NFT has been withdrawn
  tags:
    chains:
    - ETH
    exploits: null
    project:
    - ERC721
    vulnerabilities:
    - CWE-20
networks:
  block_number: '15028846'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: ^0.8.10
options: null
