info:
  description: On Apr-23-2022, AkuDreams was hacked and loses more than 34M USD. There exist two serious logic vulnerabilities. The first vulnerability can cause a DoS attack due to the missing check if the bidder is a contract. As a result, the attacker can call the revert() and stop the honest bidders from getting back their bid amount. The Second will make the project fund being locked forever due to incorrect check in the require statment.
  license: 'UNLICENSED'
  author: ['SunWeb3Sec']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/AkutarNFT_exp.sol'
    - 'https://blocksecteam.medium.com/how-akutar-nft-loses-34m-usd-60d6cb053dff'
    - 'https://etherscan.io/address/0xf42c318dbfbaab0eee040279c6a2588fa01a961d#code'
  tags: 
    chains: ['ethereum']
    project: ['nft']  
    vulnerabilities: ['lack of input validation', 'incorrect check']
    exploits: ['dos']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '14636844'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
address:
options: