address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - zhouxianyuan
  description: On Aug-09-2022, ANCH was attacked by skim token balance. The reason
    is that it supports skim() but the token transfer does not check if recipient
    and sender are the same.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/ANCH_exp.sol
  - https://twitter.com/AnciliaInc/status/1557527183966408706
  tags:
    chains:
    - bsc
    exploits:
    - skim token balance
    project:
    - token
    vulnerabilities:
    - miss check
networks:
  block_number: '20302534'
  is_forking: '1'
  node: bsc
  private_key: ''
  solidity_version: ^0.8.10
options: null
