info:
  description: On Feb-14-2022, the Build Finance DAO has been the target of a hostile governance takeover in which a malicious actor has put forward and succeeded with a proposal to take control of the Build token contract, and the loss is $470k. The attacker succeeded in the takeover by having a large enough vote in favour of the proposal and there were not enough countervotes to prevent the takeover from happening.
  license: 'UNLICENSED'
  author: ['finn79426', 'SunWeb3Sec']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/BuildF_exp.sol'
    - 'https://twitter.com/finance_build/status/1493223190071554049'
    - 'https://www.cryptotimes.io/build-finance-suffered-hostile-governance-takeover-lost-470k/'
    - 'https://etherscan.io/tx/0x544e5849b71b98393f41d641683586d0b519c46a2eeac9bcb351917f40258a85'
  tags: 
    chains: ['ethereum']
    project: ['dao']  
    vulnerabilities: [] #wip
    exploits: ['governance takeover']  #wip
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '14235712'
  is_forking: '1'
  private_key: ''
  solidity_version: '>=0.7.0 <0.9.0'
interfaces:
- IERC20.sol
address:
options: