address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - Cache-and-Burn
  description: "On Aug-01-2022, the Nomad bridge experienced an exploit causing a\
    \ loss of around $190M worth of assets. The vulnerability was in the initialization\
    \ process where the \u201CcommittedRoot\u201D is set as ZERO. Therefore, the attackers\
    \ were able to bypass the message verification process and drain the tokens from\
    \ the bridge contract."
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/NomadBridge.exp.sol
  - https://twitter.com/samczsun/status/1554252024723546112
  - https://www.certik.com/resources/blog/28fMavD63CpZJOKOjb9DX3-nomad-bridge-exploit-incident-analysis
  - https://blog.coinbase.com/nomad-bridge-incident-analysis-899b425b0f34
  root_cause: Business Logic Flaw, Incorrect acceptable merkle-root checks
  tags:
    chains:
    - ETH
    exploits: null
    project:
    - Bridge
    vulnerabilities:
    - Insufficient validation
    - Business logic issue
    - CWE-20
networks:
  block_number: '15259100'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: ^0.8.10
options: null
