address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - SunWeb3Sec
  - finn79426
  description: On Jun-16-2022, InverseFinance  recently suffered from flashloan attacks.
    This led to the loss of 53.2445 WBTC and 99,976.29 USDT. The main cause for this
    event is due to the use of insecure oracles to calculate LP price.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/InverseFinance_exp.sol
  - https://twitter.com/peckshield/status/1537382891230883841
  - https://twitter.com/SlowMist_Team/status/1537602909512376321
  - https://blocksecteam.medium.com/price-oracle-manipulation-attack-on-inverse-finance-a5544218ea91
  - https://www.certik.com/resources/blog/6LbL57WA3iMNm8zd7q111R-inverse-finance-incident-analysis
  - https://etherscan.io/tx/0x958236266991bc3fe3b77feaacea120f172c0708ad01c7a715b255f218f9313c
  root_cause: Incorrect LP price calculation via balanceOf
  tags:
    chains:
    - ETH
    exploits:
    - Flashloan
    - Price manipulation
    project:
    - Lending
    vulnerabilities: 
    - CWE-682
    - Incorrect calculation
networks:
  block_number: '14433982'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: '>=0.7.0 <0.9.0'
options: null
