info:
  description: At 03:18:38 AM +UTC on Apr-15-2022, the Rikkei Finance lending and borrowing protocol was attacked. The total impact of the exploit was 2,672 BNB or approximately $1.1M USD. The hacker found a vulnerability in the source code of the PriceOracle smart contract through which he was able to make unauthorized changes to the contract addresses. 
  license: 'UNLICENSED'
  author: ['finn79426', 'SunWeb3Sec']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Rikkei_exp.sol'
    - 'https://blockmagnates.com/rikkei-finance-hack/'
    - 'https://knownseclab.com/news/625e865cf1c544005a4bdaf2'
    - 'https://rikkeifinance.medium.com/rikkei-finance-incident-investigation-report-b5b1745b0155'
    - 'https://bscscan.com/tx/0x93a9b022df260f1953420cd3e18789e7d1e095459e36fe2eb534918ed1687492'
  tags: 
    chains: ['bsc']
    project: ['lending']  #wip
    vulnerabilities: ['access control'] #wip: CWE here
    exploits: ['price oracle manipulation']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '16956474'
  is_forking: '1'
  private_key: ''
  solidity_version: '>=0.7.0 <0.9.0'
interfaces:
address:
options: