info:
  description: On Jun-08-2022, the GymSinglePool of GymNet is hacked w/ the loss of $2.1m (~7.5K BNB). The bug is due to the lack of caller verification, which is exploited to increase the balance without making any payment.
  license: 'UNLICENSED'
  author: ['SunWeb3Sec', 'finn79426']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Gym_2_exp.sol'
    - 'https://twitter.com/peckshield/status/1534423219607719936'
    - 'https://twitter.com/1nf0s3cpt/status/1534464698069884929'
    - 'https://www.jinse.com/news/blockchain/1658455.html'
  tags: 
    chains: ['bsc']
    project: ['token', 'staking']  
    vulnerabilities: ['access control', 'cwe-284'] #lack of caller verification
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '18501049'
  is_forking: '1'
  private_key: ''
  solidity_version: '0.8.10'
interfaces:
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
address:
options: