address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - SunWeb3Sec
  - finn79426
  description: On Jun-08-2022, the GymSinglePool of GymNet is hacked w/ the loss of
    $2.1m (~7.5K BNB). The bug is due to the lack of caller verification, which is
    exploited to increase the balance without making any payment.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Gym_2_exp.sol
  - https://twitter.com/peckshield/status/1534423219607719936
  - https://twitter.com/1nf0s3cpt/status/1534464698069884929
  - https://www.jinse.com/news/blockchain/1658455.html
  root_cause: Incorrect access control
  tags:
    chains:
    - BSC
    exploits: null
    project:
    - ERC20
    vulnerabilities:
    - CWE-20
    - CWE-284
networks:
  block_number: '18501049'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: 0.8.10
options: null
