address: null
development_framework:
  framework: foundry
  script: ''
info:
  author: zhouxianyuan
  description: On Oct-18-2022, HAPY lost 115 BNB due to access control issue.
  license: MIT
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/HPAY_exp.sol
  tags:
    chains:
    - bsc
    exploits: []
    project:
    - exchange
    - gaming
    vulnerabilities:
    - CWE-284
networks:
  block_number: '22280853'
  is_forking: '1'
  node: bsc
  private_key: ''
  solidity_version: 0.8.10
options: null
