info:
  description: On Oct-01-2022 11:57:39 PM +UTC, a suspicious flashloan which has caused a slippage on project RL Token (RL), which has dropped more than >99%. 
  license: 
  author: 'zhouxianyuan'
  references:
    - 'https://twitter.com/CertiKAlert/status/1576195971003858944'
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/RL_exp.sol'
  tags: ['bsc', 'token', 'incorrect reward calculation']
development_framework:
  script: 
  framework: 'foundry'
networks:
  block_number: '21794289'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
  url: 
interfaces:
- Uniswap/IUniswapV2Router02.sol
address:
  RL: '0x4bBfae575Dd47BCFD5770AB4bC54Eb83DB088888'
  RLL: '0x335ddcE3f07b0bdaFc03F56c1b30D3b269366666'
  pair: '0xD9578d4009D9CC284B32D19fE58FfE5113c04A5e'
  USDT: '0x55d398326f99059fF775485246999027B3197955'
  dodo: '0xD7B7218D778338Ea05f5Ecce82f86D365E25dBCE'
  Router: '0x10ED43C718714eb63d5aA57B78B54704E256024E'
  cheats: '0x7109709ECfa91a80626fF3989D68f67F5b1DD12D'
options:
