address: null
development_framework:
  framework: hardhat
  script: attack.ts
info:
  author:
  - Rivaill
  description: Whitehat Gerhard Wagner submitted a critical vulnerability on October
    5th, 2021 that affected the Polygon Plasma Bridge. The vulnerability allowed an
    attacker to exit their burn transaction from the bridge multiple times, up to
    223 times. There was around ~$850M at risk. Having just $100k to launch the attack
    with would result in $22.3M in losses! This means the DepositManager for the Plasma
    Bridge could be depleted with a sufficient amount.
  license: MIT
  references:
  - https://github.com/Rivaill/CryptoVulhub/tree/master/PolygonDoubleSpend
  - https://medium.com/immunefi/polygon-double-spend-bug-fix-postmortem-2m-bounty-5a1db09db7f1
  - https://www.tofreedom.me/polygonmatic
  root_cause: The vulnerability allowed an
    attacker to exit their burn transaction from the bridge multiple times
  tags:
    chains:
    - ETH
    exploits:
    - Double spend
    project:
    - Bridge
    vulnerabilities:
    - Business logic issue
networks:
  block_number: '13260334'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: 0.8.4
options: null
