info:
  description: Whitehat Gerhard Wagner submitted a critical vulnerability on October 5th, 2021 that affected the Polygon Plasma Bridge. The vulnerability allowed an attacker to exit their burn transaction from the bridge multiple times, up to 223 times. There was around ~$850M at risk. Having just $100k to launch the attack with would result in $22.3M in losses! This means the DepositManager for the Plasma Bridge could be depleted with a sufficient amount. 
  license: 'MIT'
  author: ['Rivaill']
  references:
    - 'https://github.com/Rivaill/CryptoVulhub/tree/master/PolygonDoubleSpend'
    - 'https://medium.com/immunefi/polygon-double-spend-bug-fix-postmortem-2m-bounty-5a1db09db7f1'
    - 'https://www.tofreedom.me/polygonmatic'
  tags: 
    chains: ['ethereum']
    project: ['bridge']  
    vulnerabilities: ['business logic issue'] #wip: CWE here
    exploits: ['double spend']  
development_framework:
  script: 'attack.ts'
  framework: 'hardhat'
networks:
  block_number: '13260334'
  is_forking: '1'
  private_key: ''
  solidity_version: '0.8.4'
interfaces:
address:
options: