address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - SunWeb3Sec
  description: On Mar-20-2022, Uno Re's partner-Umbrella Network announced that the
    LP tokens staked in their Polar Stream staking contracts on Ethereum and BNB Chain
    are drained from both of the contracts. Reportedly, the hacker then withdrew liquidity
    using those stolen LP tokens from both the UMB-ETH Uniswap and the UMB-BNB Pancakeswap
    pools. The investigation revealed that the hack was possible due to an underflow
    bug in the smart contract code.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Umbrella_exp.sol
  - https://medium.com/uno-re/umbrella-network-hacked-700k-lost-97285b69e8c7
  - https://etherscan.io/tx/0x33479bcfbc792aa0f8103ab0d7a3784788b5b0e1467c81ffbed1b7682660b4fa
  tags:
    chains:
    - ethereum
    exploits: []
    project:
    - token
    - staking
    vulnerabilities:
    - underflow
networks:
  block_number: '14421983'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: ^0.8.10
options: null
