info:
  description: On Nov-01-2022, ShadowFi suffered an exploit possibly due to a vulnerability of SDF token which allows the token can be burnt by anybody, the exploiter grabbed ~1,078 $BNB (~$301k). $SDF has dropped 98.5%.
  license: 'MIT'
  author: ['zhouxianyuan']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Shadowfi_exp.sol'
    - 'https://twitter.com/PeckShieldAlert/status/1565549688509861888'
    - 'https://bscscan.com/tx/0xe30dc75253eecec3377e03c532aa41bae1c26909bc8618f21fb83d4330a01018'
  tags: 
    chains: ['bsc']
    project: ['token']  
    vulnerabilities: ['access control', 'CWE-284'] 
    exploits: ['price manipulation']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '20969095'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
address:
options: