address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - finn79426
  description: On Jul-25-2022, LPC was under a flashloan attack. Since the ledger
    balance is not updated in the _transfer function, but is modified directly on
    the original recipientBalance, resulting in an increase in the attacker balance.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/LPC.exp.sol
  - https://www.panewslab.com/zh_hk/articledetails/uwv4sma2.html
  - https://twitter.com/BeosinAlert/status/1551535854681718784
  root_cause: Incorrect recipient balance check, did not check sender!=recipient in transfer
  tags:
    chains:
    - BSC
    exploits:
    - Flashloan
    project:
    - ERC20
    vulnerabilities:
    - CWE-20
networks:
  block_number: '19852596'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: ^0.8.10
options: null
