info:
  description: On Oct-20-2022, this Tx (0x9f4ef3cc55b016ea6b867807a09f80d1b2e36f6cd6fccfaf0182f46060332c57) minted 1,000,000,000,000 $BEGO token, and then swapped to 12 WBNB, which started the drop of the $BEGO price on pancake swap. The main reason is the BGEO token's mint() is fundamentally flawed and allows for unlimited mints!
  license: 'UNLICENSED'
  author: 'zhouxianyuan'
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/BEGO_exp.sol'
    - 'https://twitter.com/AnciliaInc/status/1582828751250784256'
    - 'https://twitter.com/peckshield/status/1582892058800685058'
  tags: 
    chains: ['bsc']
    project: ['token']  
    vulnerabilities: ['CWE-305'] #wip: CWE here
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '22315679'
  is_forking: '1'
  private_key: ''
  solidity_version: 0.8.10
  node: 'bsc'
interfaces:
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
- PancakeSwap/IPancakePair.sol
address:
options: