info:
  description: On Oct-20-2022, HEALTH token (0x32b166e082993af6598a89397e82e123ca44e74e) on BSC has been attacked. The project is susceptible to price manipulation vulnerability. 
  license: 'UNLICENSED'
  author: 'zhouxianyuan'
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/HEALTH_exp.sol'
    - 'https://twitter.com/BlockSecTeam/status/1583073442433495040'
  tags: 
    chains: ['bsc']
    project: ['token']  
    vulnerabilities: [] #wip: CWE, 'Transfer Logic Flaw'
    exploits: ['price oracle manipulation']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '22337425'
  is_forking: '1'
  private_key: ''
  solidity_version: 0.8.10
interfaces:
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
- PancakeSwap/IPancakePair.sol
address:
options: