address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - SunWeb3Sec
  - 0xDatapunk
  description: On Mar-29-2022, ~$624M was stolen from Ronin Network. The Sky Mavis
    validators were compromised and there exists a vulnerability that led to the attacker
    gaining control of the required fifth signature.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Ronin_exp.sol
  - https://rekt.news/ronin-rekt/
  - https://etherscan.io/tx/0xc28fad5e8d5e0ce6a2eaf67b6687be5d58113e16be590824d6cfa1a94467d0b7
  - https://etherscan.io/tx/0xed2c72ef1a552ddaec6dd1f5cddf0b59a8f37f82bdda5257d9c7c37db7bb9b08
  tags:
    chains:
    - ethereum
    exploits:
    - ''
    project:
    - bridge
    vulnerabilities: []
networks:
  block_number: '14442834'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: '>=0.7.0 <0.9.0'
options: null
