address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - SunWeb3Sec
  - finn79426
  description: "On Apr-30-2022, Various Rari Fuse polls of Fei protocol was exploited\
    \ and the total loss is ~$80 million. The root cause of this attack stems from\
    \ a Reentrancy security loophole where an attacker is able to borrow assets yet\
    \ withdraw all the deposited collateral. Specifically, the attacker flashloaned\
    \ multiple tokens/WETH as collateral and borrowed assets from the pool. However,\
    \ as the code implementation does not apply the practice of the check-effect-interaction\
    \ pattern, the result means that the attacker can invoke \u201CexitMarket()\u201D\
    \ to withdraw all his collateral as the borrow records are not properly updated."
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Rari_exp.t.sol
  - https://certik.medium.com/fei-protocol-incident-analysis-8527440696cc
  - https://twitter.com/peckshield/status/1520369315698016256
  - https://etherscan.io/tx/0xab486012f21be741c9e674ffda227e30518e8a1e37a5f1d58d0b0d41f6e76530
  tags:
    chains:
    - ethereum
    exploits:
    - flashloan
    project:
    - token
    - lending
    vulnerabilities:
    - reentrancy
networks:
  block_number: '14684813'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: '>=0.7.0 <0.9.0'
options: null
