info:
  description: On Mar-15-2022, Hundred Finance and Agave, lending protocols on the Gnosis Chain, were hit by reentrancy attacks with the loss of $1.7 million.
  license: 'UNLICENSED'
  author: ['SunWeb3Sec']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/HundredFinance_exp.sol'
    - 'https://medium.com/immunefi/a-poc-of-the-hundred-finance-heist-4121f23a098'
    - 'https://gnosisscan.io/tx/0x534b84f657883ddc1b66a314e8b392feb35024afdec61dfe8e7c510cfac1a098'
  tags: 
    chains: ['gnosis']
    project: ['lending']  
    vulnerabilities: ['reentrancy'] #wip: CWE here
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '21120319'
  is_forking: '1'
  private_key: ''
  solidity_version: 0.8.4
interfaces:
- Uniswap/IUniswapV2Router01.sol
- Uniswap/IUniswapV2Router02.sol
- Uniswap/IUniswapV2Factory.sol
- Uniswap/IUniswapV2Pair.sol
address:
options: