address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - zhouxianyuan
  description: On Nov-04-2022, Bvaults was under a price manipulation attack. The
    attacker gained 16 $WBNB. The root cause is the convertDustToEarned function of
    the BvaultsStrategy contract does not do price checks. Also, small trading pairs
    are sensitive to price fluctuations in swapping volume.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/BDEX_exp.sol
  - https://twitter.com/BeosinAlert/status/1588579143830343683
  tags:
    chains:
    - bsc
    exploits:
    - price manipulation
    project:
    - token
    vulnerabilities:
    - CWE-20
networks:
  block_number: '22629431'
  is_forking: '1'
  node: bsc
  private_key: ''
  solidity_version: ^0.8.10
options: null
