address: null
development_framework:
  framework: foundry
  script: null
info:
  author: zhouxianyuan
  description: On Oct-14-2022, the MEV bot was exploited and the loss is aroud 187.75
    WETH. The root cause is the MEV bot added its own balance into the flash loan
    swap.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/MEVa47b_exp.sol
  - https://twitter.com/BlockSecTeam/status/1580779311862190080
  - https://twitter.com/AnciliaInc/status/1580705036400611328
  - https://etherscan.io/tx/0x35ecf595864400696853c53edf3e3d60096639b6071cadea6076c9c6ceb921c1
  root_cause: Insufficient validation
  tags:
    chains:
    - ETH
    exploits:
    - Flashloan
    project:
    - MEV
    vulnerabilities:
    - CWE-20
networks:
  block_number: '15741332'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: 0.8.10
options: null
