address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - finn79426
  - SunWeb3Sec
  description: On Mar-27-2022, the staking DeFi project Revest Finance on Ethereum
    was attacked due to the ERC-1155 call-back mechanism. Roughly $2M worth of tokens
    (namely BLOCKS, ECO, LYXe, and RENA) were stolen.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Revest_exp.sol
  - https://blocksecteam.medium.com/revest-finance-vulnerabilities-more-than-re-entrancy-1609957b742f
  - https://twitter.com/BlockSecTeam/status/1508065573250678793
  - https://etherscan.io/tx/0xe0b0c2672b760bef4e2851e91c69c8c0ad135c6987bbf1f43f5846d89e691428
  tags:
    chains:
    - ethereum
    exploits: []
    project:
    - token
    - staking
    vulnerabilities:
    - reentrancy
networks:
  block_number: '14465356'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: '>=0.7.0 <0.9.0'
options: null
