address: null
development_framework:
  framework: hardhat
  script: attack.ts
info:
  author:
  - Rivaill
  description: On Dec-21-2022, the Visor Finance was exploited and the hacker gained
    more than 133 ETH (~$500,000). The vulnerability is caused by arbitrary external
    call.
  license: MIT
  references:
  - https://github.com/Rivaill/CryptoVulhub/tree/master/VisorFinance20211221
  - https://twitter.com/VisorFinance/status/1473306777131405314
  - https://www.tofreedom.me/visorfinance-re-hack
  root_cause: Arbirary external call
  tags:
    chains:
    - ETH
    exploits: null
    project: null
    vulnerabilities:
    - Reentrancy
    - Arbitrary call
networks:
  block_number: '13849006'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: 0.8.4
options: null
