info:
  description: On Mar-03-2022, a serious vulnerability in TreasureDao's NFT trading platform was reported and the total loss is $1 million. The main cause of this vulnerability is a failure to recognize that the incoming _quantity parameter is not 0 prior to the transfer of NFTs. As a result, NFTs were directly transferred when calculating the price for purchases since the calculated fees were 0.
  license: 'UNLICENSED'
  author: ['finn79426', 'SunWeb3Sec']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/TreasureDAO_exp.sol'
    - 'https://slowmist.medium.com/analysis-of-the-treasuredao-zero-fee-exploit-73791f4b9c14'
    - 'https://arbiscan.io/tx/0x82a5ff772c186fb3f62bf9a8461aeadd8ea0904025c3330a4d247822ff34bc02'
  tags: 
    chains: ['arbitrum']
    project: ['nft']  
    vulnerabilities: ['logic issue'] #wip: zero fee
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '7322694'
  is_forking: '1'
  private_key: ''
  solidity_version: '0.8.10'
interfaces:
- IERC721.sol
address:
options: