info:
  description: On Mar-05-2022, the Bacon Protocol was hacked w/ ~$1M loss. The hack is made possible due to a reentrancy bug in the lend() routine so that the hacker can get more lending credits via re-entering the lend() routine.
  license: 'UNLICENSED'
  author: ['finn79426', 'SunWeb3Sec']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Bacon_exp.sol'
    - 'https://twitter.com/peckshield/status/1500105933128495108'
    - 'https://etherscan.io/tx/0xacfcaa8e1c482148f9f2d592c78ca7a27934c7333dab31978ed0aef333a28ab6'
    - 'https://etherscan.io/tx/0x7d2296bcb936aa5e2397ddf8ccba59f54a178c3901666b49291d880369dbcf31'
  tags: 
    chains: ['ethereum']
    project: ['lending']  #wip
    vulnerabilities: ['reentrancy']
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '14326931'
  is_forking: '1'
  private_key: ''
  solidity_version: '>=0.7.0 <0.9.0'
interfaces:
- PancakeSwap/IERC20.sol
- PancakeSwap/IPancakePair.sol
address:
options: