address:
  BXH: '0x6D1B7b59e3fab85B7d3a3d86e505Dd8e349EA7F3'
  bxhRouter: '0x6A1A6B78A57965E8EF8D1C51d92701601FA74F01'
  bxhtokenstaking: '0x27539B1DEe647b38e1B987c41C5336b1A8DcE663'
  bxhusdtpair: '0x919964B7f12A742E3D33176D7aF9094EA4152e6f'
  pancakeRouter: '0x10ED43C718714eb63d5aA57B78B54704E256024E'
  usdt: '0x55d398326f99059fF775485246999027B3197955'
  usdtwbnbpair: '0x16b9a82891338f9bA80E2D6970FddA79D1eb0daE'
  vUSDT: '0x19195aC5F36F8C75Da129Afca8f92009E292B84a'
  wbnb: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c'
development_framework:
  framework: foundry
  script: ''
info:
  author: funnbee
  description: On Sep-28-2022, BXH's TokenStakingPoolDelegate contract, which was
    updated after the last attack, was attacked again by the flashloan, which lost
    40,085 USDT and the attacker made 31,794 USDT after paying off the flashloan fees.
    This attack was caused by the use of the getITokenBonusAmount function in the
    contract getReserves() in the contract's getITokenBonusAmount function to obtain
    instantaneous quotes, allowing the attacker to manipulate the quotes to complete
    the profit.
  license: null
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/BXH_exp.sol
  - https://www.jinse.com/lives/319392.html
  - https://bscscan.com/tx/0xa13c8c7a0c97093dba3096c88044273c29cebeee109e23622cd412dcca8f50f4
  tags:
    chains:
    - bsc
    exploits:
    - flashloan
    - price oracle manipulation
    project:
    - token
    - staking
    vulnerabilities: []
networks:
  block_number: '21727289'
  is_forking: '1'
  node: bsc
  private_key: ''
  solidity_version: ^0.8.10
options: null
