address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - zhouxianyuan
  description: On Oct-12-2022, ATK on BSC was attacked, the hackers abused Flashloan
    to attack the reward distribution function.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/ATK_exp.sol
  - https://twitter.com/BlockSecTeam/status/1580095325200474112
  root_cause: Incorrect price calculation via balanceOf
  tags:
    chains:
    - BSC
    exploits:
    - Flashloan
    - Price manipulation
    project:
    - ERC20
    vulnerabilities:
    - CWE-682
    - Business logic issue
networks:
  block_number: '22102838'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: 0.8.10
options: null
