info:
  description: On Oct-12-2022, ATK on BSC was attacked, the hackers abused Flashloan to attack the reward distribution function.
  license: 'UNLICENSED'
  author: ['zhouxianyuan']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/ATK_exp.sol'
    - 'https://twitter.com/BlockSecTeam/status/1580095325200474112'
  tags: 
    chains: ['bsc']
    project: ['token'] 
    vulnerabilities: ['business logic issue']
    exploits: ['flashloan']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '22102838'
  is_forking: '1'
  private_key: ''
  solidity_version: 0.8.10
interfaces:
- PancakeSwap/IERC20.sol
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
- PancakeSwap/IPancakePair.sol
address:
options: