address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - zhouxianyuan
  description: On Nov-21-2022, SportsDao1 was exploited via flashload. The attacker
    took advantage of the rewards system and gained ~$13.6k.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/SDAO_exp.sol
  - https://twitter.com/8olidity/status/1594693686398316544
  - https://twitter.com/CertiKAlert/status/1594615286556393478
  root_cause: Improper reward system
  tags:
    chains:
    - BSC
    exploits:
    - Flashloan
    project:
    - DAO
    vulnerabilities:
    - Business logic issue
networks:
  block_number: '23241440'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: ^0.8.10
options: null
