info:
  description: On Nov-04-2022, Bvaults was under a price manipulation attack. The attacker gained 16 $WBNB. The root cause is the convertDustToEarned function of the BvaultsStrategy contract does not do price checks. Also, small trading pairs are sensitive to price fluctuations in swapping volume. 
  license: 'UNLICENSED'
  author: ['zhouxianyuan']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/BDEX_exp.sol'
    - 'https://twitter.com/BeosinAlert/status/1588579143830343683'
  tags: 
    chains: ['bsc']
    project: ['token']  
    vulnerabilities: ['CWE-20'] #wip: CWE here
    exploits: ['price manipulation']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '22629431'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
address:
options: