info:
  description: On Oct-18-2022, HAPY lost 115 BNB due to access control issue. 
  license: 'MIT'
  author: 'zhouxianyuan'
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/HPAY_exp.sol'
  tags: 
    chains: ['bsc']
    project: ['exchange', 'gaming']  
    vulnerabilities: [''CWE-284']
    exploits: [] #wip
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '22280853'
  is_forking: '1'
  private_key: ''
  solidity_version: 0.8.10
interfaces:
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
address:
options: