address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - zhouxianyuan
  description: On Oct-24-2022, contract 0x940cE652A51EBadB5dF09d605dBEDA95fDcF697b
    lost $600 due to Arbitrary External Call Vulnerability.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/MulticallWithoutCheck_exp.sol
  root_cause: Arbitrary external call
  tags:
    chains:
    - Polygon
    exploits: null
    project: null
    vulnerabilities:
    - Arbitrary call
networks:
  block_number: '34743770'
  is_forking: '1'
  node: polygon
  private_key: null
  solidity_version: ^0.8.10
options: null
