info:
  description: On Mar-17-2022, the APE token has been attacked by the MEVor with loss $1.1 million. Someone discovered a way to claim the airdrop by using NFTs that they did not own at the time. They used the special way the airdrop works to carry it out. It was a very effective approach, earning them $1.1 million in ApeCoin. In particular, the attacker can borrow BAYC tokens that can be redeemed to NFTs, and then use these NFTs to claim the AirDrop. After that, the attacker mint the BAYC tokens using the BAYC NFTs to return the flash loan.
  license: 'UNLICENSED'
  author: ['SunWeb3Sec']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Bayc_apecoin_exp.sol'
    - 'https://etherscan.io/tx/0xeb8c3bebed11e2e4fcd30cbfc2fb3c55c4ca166003c7f7d319e78eaab9747098'
    - 'https://news.coincu.com/73892-the-flashloan-attack-on-the-ape-airdrop-to-claim-1-1-million-of-ape-tokens/'
  tags: 
    chains: ['ethereum']
    project: ['token', 'nft']  
    vulnerabilities: [] #wip: CWE here
    exploits: ['flashloan']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '14403948'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
address:
options: