address: null
development_framework:
  framework: foundry
  script: attack.ts
info:
  author:
  - unknown
  description: On Nov-16-2022, UEarnPool staking contract lost 16,038 USDT by a flashloan
    attack.
  license: MIT
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/UEarnPool_exp.sol
  - https://twitter.com/CertiKAlert/status/1593094922160128000
  root_cause: null
  tags:
    chains:
    - BSC
    exploits:
    - Flashloan
    project:
    - Staking
    vulnerabilities: null
networks:
  block_number: '23120167'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: ^0.8.10
options: null
