info:
  description: On Nov-16-2022, UEarnPool staking contract lost 16,038 USDT by a flashloan attack. 
  license: 'MIT'
  author: ['unknown']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/UEarnPool_exp.sol'
    - 'https://twitter.com/CertiKAlert/status/1593094922160128000'
  tags: 
    chains: ['bsc']
    project: ['staking']  
    vulnerabilities: [] #wip: CWE here
    exploits: ['flashloan']  
development_framework:
  script: 'attack.ts'
  framework: 'foundry'
networks:
  block_number: '23120167'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
address:
options: