address: null
development_framework:
  framework: foundry
  script: null
info:
  author: SunWeb3Sec
  description: On Oct-14-2022, EFLeverVault contract was hit by a Flashloan attack
    that resulted in a cumulative profit of 480 Ether from the MEV Bot and 268 Ether
    from the hackers.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/INUKO_exp.sol
  - https://twitter.com/AnciliaInc/status/1587848874076430336
  root_cause: Insufficient validation
  tags:
    chains:
    - ETH
    exploits:
    - Flashloan
    project:
    - Yield
    vulnerabilities: 
    - CWE-20
networks:
  block_number: '15746199'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: 0.8.10
options: null
