address: null
development_framework:
  framework: foundry
  script: ''
info:
  author: SunWeb3Sec
  description: On Oct-14-2022, EFLeverVault contract was hit by a Flashloan attack
    that resulted in a cumulative profit of 480 Ether from the MEV Bot and 268 Ether
    from the hackers.
  license: UNLICENSED
  references:
  - url
  - cve
  tags:
    chains:
    - ethereum
    exploits:
    - flashloan
    project:
    - vault
    vulnerabilities: []
networks:
  block_number: '15746199'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: 0.8.10
options: null
