info:
  description: On Nov-23-2022, $NUM of the numbersprotocol seems to be exploited with loss $13k due to the token is incompatible with the MultichainOrg Router. Specifically, $NUM does NOT implement the permit() function required by the Router; meanwhile, the token has a default fallback() which can be exploited.
  license: 'UNLICENSED'
  author: ['zhouxianyuan']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/NUM_exp.sol'
    - 'https://twitter.com/BlockSecTeam/status/1595346020237352960'
  tags: 
    chains: ['ethereum']
    project: ['token']  
    vulnerabilities: ['incompatible'] #wip: CWE here
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '16029969'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
- Uniswap/IUniswapV2Router01.sol
- Uniswap/IUniswapV2Router02.sol
address:
options: