info:
  description: On Nov-09-2022, the brahTOPG project on the ETH chain was attacked, leading to the loss of $89,879. The root cause of this attack is that the Zapper contract is rigorously checking for incoming user data, leading to an arbitrary external call issue. The attackers exploit this vulnerability to steal funds from users who are still authorized to the contract.
  license: 'UNLICENSED'
  author: ['zhouxianyuan']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/BrahTOPG_exp.sol'
    - 'https://twitter.com/SlowMist_Team/status/1590685173477101570'
  tags: 
    chains: ['ethereum']
    project: ['token', 'staking']  
    vulnerabilities: ['CWE-470'] #wip: CWE here
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '15933794'
  is_forking: '1'
  private_key: ''
  solidity_version: 0.8.10
interfaces:
- Uniswap/IUniswapV2Router01.sol
- Uniswap/IUniswapV2Router02.sol
address:
options: