address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - SunWeb3Sec
  - 0xDatapunk
  description: On Jan-27-2022, the Qubit protocol was subject to an exploit to the
    QBridge deposit function with the loss of $80 million. Qubit allows for cross-chain
    collateralisation, locking assets on Ethereum to borrow against on BSC via the
    QBridge deposit function. The attacker took advantage of a logic bug in the code
    which made xETH available for use on BSC without having deposited ETH on Ethereum.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Qubit_exp.sol
  - https://rekt.news/qubit-rekt/
  - https://medium.com/@QubitFin/protocol-exploit-report-305c34540fa3
  - https://etherscan.io/address/0xd01ae1a708614948b2b5e0b7ab5be6afa01325c7
  - https://etherscan.io/tx/0xac7292e7d0ec8ebe1c94203d190874b2aab30592327b6cc875d00f18de6f3133
  - https://bscscan.com/tx/0x50946e3e4ccb7d39f3512b7ecb75df66e6868b9af0eee8a7e4b61ef8a459518e
  tags:
    chains:
    - ethereum
    exploits: []
    project:
    - bridge
    - lendng
    vulnerabilities:
    - logic issue
networks:
  block_number: '14090169'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: 0.8.10
options: null
