info:
  description: On Nov-29-2022, the SEAMAN project was exploited by flashloan attack with total loss ~$7.8k. The exploiter took advantage of a vulnerability in the way SEAMAN handles GVC distribution on LP deposits. The exploit caused a spike in GVC.
  license: 'MIT'
  author: ['zhouxianyuan']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/SEAMAN_exp.sol'
    - 'https://twitter.com/peckshield/status/1597493955939405825'
    - 'https://twitter.com/CertiKAlert/status/1597513374841044993'
    - 'https://twitter.com/BeosinAlert/status/1597535796621631489'
  tags: 
    chains: ['bsc']
    project: ['token']
    vulnerabilities: ['business logic flaw'] #wip: CWE here
    exploits: ['flashloan', 'price oracle manipulation']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '23467515'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
- PancakeSwap/IERC20.sol
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
address:
options:s