info:
  description: 'On Sep-08-2022, the project Ragnarok Online Invasion - $ROI has a slippage for over 98%. The open access vulnerability of transferOwnership() appears to have been exploited. '
  license: 
  author: 'unknown'
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/ROI_exp.sol'
    - 'https://twitter.com/BlockSecTeam/status/1567746825616236544'
    - 'https://twitter.com/CertiKAlert/status/1567754904663429123'
    - 'https://www.panewslab.com/zh_hk/articledetails/mbzalpdi.html'
    - 'https://medium.com/quillhash/decoding-ragnarok-online-invasion-44k-exploit-quillaudits-261b7e23b55'
  tags: ['bsc', 'broken access control']  
development_framework:
  script: 'attack.ts'
  framework: 'hardhat'
networks:
  block_number: '21143795'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
  url: ''
interfaces:
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
- PancakeSwap/IPancakePair.sol
address:
  ROI: '0xE48b75dc1b131fd3A8364b0580f76eFD04cF6e9c'
  busd: '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56'
  wbnb: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c'
  pancakeRouter: '0x10ED43C718714eb63d5aA57B78B54704E256024E'
  busdroiPair: '0x745D6Dd206906dd32b3f35E00533AD0963805124'
options:
  burn_amount: '19999'
  number_of_burn_operations: '11'
  number_of_swap_operations: '4'
  swap_amount: '19999'