address:
  DPC: '0xB75cA3C3e99747d0e2F6e75A9fBD17F5Ac03cebE'
  Pair: '0x79cD24Ed4524373aF6e047556018b1440CF04be3'
  Router: '0x10ED43C718714eb63d5aA57B78B54704E256024E'
  USDT: '0x55d398326f99059fF775485246999027B3197955'
  WBNB: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c'
development_framework:
  framework: foundry
  script: ''
info:
  author: zhouxianyuan
  description: On Sep-09-2022, $DPC was hacked for ~$103,755. The attacker first used
    the tokenAirdop function in the DPC token contract to prepare for claiming the
    rewards, then swapped $USDT for $DPC, added liquidity to obtain LP tokens, and
    then staked LP tokens in the token contract.
  license: null
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/DPC_exp.sol
  - https://twitter.com/BeosinAlert/status/1568429355919089664
  - https://bscscan.com/address/0x2109bbecB0a563e204985524Dd3DB2F6254AB419
  - https://learnblockchain.cn/article/4733
  tags:
    chains:
    - bsc
    exploits: []
    project:
    - token
    - staking
    vulnerabilities:
    - incorrect reward calculation
networks:
  block_number: '21179209'
  is_forking: '1'
  node: bsc
  private_key: ''
  solidity_version: ^0.8.10
  url: ''
options: null
