info:
  description: 'On Sep-30-2022, a reentrancy bug on Thunder Brawl was found, which results in the rewards being drained.'
  license: 
  author: 'zhouxianyuan'
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/THB_exp.sol'
    - 'https://twitter.com/peckshield/status/1575890733373849601'
  tags: 
    chains: ['bsc']
    project: ['erc721']  
    vulnerabilities: ['reentrancy', 'CWE-841']
    exploits: [] 
development_framework:
  script: 
  framework: 'foundry'
networks:
  block_number: '21785004'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
  url: 
interfaces:
address:
  houseWallet: '0xae191Ca19F0f8E21d754c6CAb99107eD62B6fe53'
options:
