address:
  houseWallet: '0xae191Ca19F0f8E21d754c6CAb99107eD62B6fe53'
development_framework:
  framework: foundry
  script: null
info:
  author: zhouxianyuan
  description: On Sep-30-2022, a reentrancy bug on Thunder Brawl was found, which
    results in the rewards being drained.
  license: null
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/THB_exp.sol
  - https://twitter.com/peckshield/status/1575890733373849601
  tags:
    chains:
    - bsc
    exploits: []
    project:
    - erc721
    vulnerabilities:
    - reentrancy
    - CWE-841
networks:
  block_number: '21785004'
  is_forking: '1'
  node: bsc
  private_key: ''
  solidity_version: ^0.8.10
  url: null
options: null
