address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - zhouxianyuan
  description: On Jan-17-2022, the VTF Token on BSC (0xc6548caf18e20f88cc437a52b6d388b0d54d830d)
    has been attacked. The attacker got a profit of around 58K USD. There is a bug
    in VTF's contract to receive holding rewards. Under normal circumstances, users
    can claim $VTF token holding rewards via the updateUserBalance function. However,
    the function does not determine how long the user has held the token.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/VTF_exp.sol
  - https://twitter.com/BlockSecTeam/status/1585575129936977920
  - https://twitter.com/peckshield/status/1585572694241988609
  - https://twitter.com/BeosinAlert/status/1585587030981218305
  root_cause: Not determine how long the user has held the token
  tags:
    chains:
    - BSC
    exploits:
    - Flashloan
    project:
    - ERC20
    - Reward
    vulnerabilities:
    - Business logic issue
networks:
  block_number: '22535101'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: ^0.8.10
options: null
