address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - finn79426
  - SunWeb3Sec
  description: On Apr-24-2022, the Wiener DOGE project was maliciously exploited,
    resulting in a loss of US$30,000 (equivalent to approximately RMB 126,000). Attackers
    exploited the inconsistency between WDODGE's charging mechanism and the exchange
    pool to launch the attack. The root cause of the incident is that the sender's
    LP pair is not excluded from the transfer fee through the tightened token contract.
    As a result, the attacker is able to drain the deflationary tokens in the LP pair,
    which in turn causes the pair price to become unbalanced.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Wdoge_exp.sol
  - https://coinyuppie.com/four-combinations-of-hackers-analysis-of-attacks-on-wiener-doge-last-kilometer-medamon-and-pidao-projects/
  - https://twitter.com/solid_group_1/status/1519034573354676224
  - https://bscscan.com/tx/0x4f2005e3815c15d1a9abd8588dd1464769a00414a6b7adcbfd75a5331d378e1d
  root_cause: the sender's
    LP pair is not excluded from the transfer fee through the tightened token contract
  tags:
    chains:
    - BSC
    exploits:
    - Flashloan
    project:
    - Deflationary token
    vulnerabilities:
    - CWE-20
networks:
  block_number: '17248705'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: 0.8.10
options: null
