address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - 0xDatapunk
  - finn79426
  - SunWeb3Sec
  description: On Jan-18-2022, Multichain's users were hacked by several attackers
    groups, all abusing the same vulnerability in Multichain (previously AnySwap)
    smart contract. The attackers were able to steal tokens valued at millions of
    US Dollars. The vulnerable function was not actually used and could have been
    removed to begin with. And the vulnerable function did not validate that the token
    input parameter is indeed of a valid Multichain token, and did not explicitly
    verify that it indeed successfully calls the non-mandatory ERC20 permit() function.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Anyswap_poc.t.sol
  - https://medium.com/zengo/without-permit-multichains-exploit-explained-8417e8c1639b
  - https://twitter.com/PeckShieldAlert/status/1483363515411099651
  - https://etherscan.io/tx/0xe50ed602bd916fc304d53c4fed236698b71691a95774ff0aeeb74b699c6227f7
  tags:
    chains:
    - ethereum
    exploits:
    - flashloan
    - price oracle manipulation
    project:
    - dex
    vulnerabilities:
    - lack of validation
    - dead code
networks:
  block_number: '14037236'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: 0.8.10
options: null
