info:
  description: On Jan-11-2022, Whitehat Tommaso Pifferi submitted a vulnerability in Redacted Cartel. This vulnerability would have allowed a malicious attacker to assign a user's allowance to themselves, enabling the attacker to steal that user's funds. Funds at risk were just under $6 million dollars. Redacted patched the bug and paid the whitehat $560,000 for his find.
  license: 'UNLICENSED'
  author: ['zhouxianyuan', 'zzzuhaibmohd']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/RedactedCartel_exp.sol'
    - 'https://medium.com/immunefi/redacted-cartel-custom-approval-logic-bugfix-review-9b2d039ca2c5'
  tags: 
    chains: ['ethereum']
    project: ['token']  
    vulnerabilities: ['logic issue']
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '13908185'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
address:
options: