address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - finn79426
  - SunWeb3Sec
  description: On Mar-15-2022, Deus Finance was exploited and loss is 200,000 DAI
    and 1101.8 ETH. The hack is made possible due to the flashloan-assisted manipulation
    of price oracle that reads from the StableV1 AMM - USDC/DEI pair. The manipulated
    price of collateral DEI is then used to borrow and drain the pool.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/deus_exp.sol
  - https://twitter.com/peckshield/status/1519531866109317121
  - https://ftmscan.com/tx/0xe374495036fac18aa5b1a497a17e70f256c4d3d416dd1408c026f3f5c70a3a9c
  root_cause: Incorrect price calculation via balanceOf
  tags:
    chains:
    - fantom
    exploits:
    - Flashloan
    - Price manipulation
    project:
    - DAO
    vulnerabilities:    
    - CWE-682
    - Business logic issue
networks:
  block_number: '37093708'
  is_forking: '1'
  node: fantom
  private_key: null
  solidity_version: 0.8.10
options: null
