address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - 0xDatapunk
  description: On Feb-06-2022, Meter was hacked and the loss is $4.3 million. This
    project used an unaffiliated fork of ChainBridge and introduced a new function
    depositEth() which has a vulnerability. The hacker can send an arbitrary amount
    in the calldata, which gets passed on the handler's deposit.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Meter_exp.sol
  - https://twitter.com/ishwinder/status/1490227406824685569
  - https://blog.chainsafe.io/breaking-down-the-meter-io-hack-a46a389e7ae4
  root_cause: Insufficient validation
  tags:
    chains:
    - Moonriver
    exploits: null
    project:
    - Bridge
    vulnerabilities:
    - CWE-20
networks:
  block_number: '1442490'
  is_forking: '1'
  node: moonriver
  private_key: null
  solidity_version: 0.8.10
options: null
