info:
  description: On Oct-17-2022, $PLTD suffers a price manipulation attack with a profit of 24,497 $BUSD for the hacker. 
  license: 'MIT'
  author: 'zhouxianyuan'
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/PLTD_exp.sol'
    - 'https://twitter.com/BeosinAlert/status/1582181583343484928'
  tags: 
    chains: ['bsc']
    project: ['token']  
    vulnerabilities: [] #wip: CWE here
    exploits: ['price oracle manipulation']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '22252045'
  is_forking: '1'
  private_key: ''
  solidity_version: 0.8.10
interfaces:
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
- PancakeSwap/IPancakePair.sol
address:
options: