info:
  description: On Oct-25-2022, ULME Token was attacked (https://phalcon.blocksec.com/tx/bsc/0xdb9a13bc970b97824e082782e838bdff0b76b30d268f1d66aac507f1d43ff4ed), and the attacker gained around 50,646 BUSD. It's an indirect price manipulation attack caused by unrestricted access control.
  license: 'UNLICENSED'
  author: ['fala13']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/ULME.sol'
    - 'https://twitter.com/BlockSecTeam/status/1584839309781135361'
    - 'https://twitter.com/BeosinAlert/status/1584888021299916801'
  tags: 
    chains: ['bsc']
    project: ['token']  
    vulnerabilities: ['access control', 'CWE-284']
    exploits: ['flashloan', 'price oracle manipulation']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '22476695'
  is_forking: '1'
  private_key: ''
  solidity_version: ^0.8.10
interfaces:
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
- PancakeSwap/IPancakePair.sol
address:
options: