address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - finn79426
  description: On Jul-14-2022, the SpaceGodzilla project on BSC Chain has been hit
    by a flash loan attack. Hackers use flash loans to borrow large amounts of funds
    to manipulate the price of platform coins in the PancakeSwap trading pool, and
    exploited the vulnerabilities in the project to attack. This attack hacker arbitrage
    25,378.78BUSD.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/SpaceGodzilla.exp.sol
  - https://mobile.twitter.com/BlockSecTeam/status/1547456591900749824
  - https://medium.com/numen-cyber-labs/spacegodzilla-attack-event-analysis-d29a061b17e1
  - https://learnblockchain.cn/article/4396
  root_cause: Incorrect access control
  tags:
    chains:
    - BSC
    exploits:
    - Flashloan
    - Price manipulation
    project:
    - ERC20
    vulnerabilities:
    - CWE-767
networks:
  block_number: '19523980'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: ^0.8.10
options: null
