info:
  description: On May-24-2022, The Hackerdao token on BSC has been attacked. The attack is due to incorrect handling of the Uniswap V2 pair logic in the token contract. In the _transfer function, the total amount of the transfer will first be reduced from the sender's account. Then if the recipient address is the designated Uniswap pair (BSCUSD-Hackerdao pair), an extra amount of fee will be further reduced from the sender. It results in a typical pattern of token attacks, if the balance of the Uniswap pair can be reduced without any swap (i.e. a difference between accounted reserves and real token balances), there is an opportunity of price manipulation. The attack is done by skimming from the WBNB-Hackerdao pair to the BSCUSD-Hackerdao pair, causing an imbalanced price.
  license: 'UNLICENSED'
  author: ['zhouxianyuan']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/HackDao_exp.sol'
    - 'https://twitter.com/BlockSecTeam/status/1529084919976034304'
  tags: 
    chains: ['bsc']
    project: ['token']  
    vulnerabilities: [] #wip: CWE here
    exploits: ['price oracle manipulation']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '18073756'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
- PancakeSwap/IERC20.sol
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
- PancakeSwap/IPancakePair.sol
address:
options: