address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - SunWeb3Sec
  - 0xDatapunk
  - finn79426
  description: On Jun-23-2022, A hacker stole $100 million from the bridge connecting
    Ethereum and harmonyprotocol. The hacker probably managed to get access to the
    2 private keys that are part of the multisig which can calls unlock() on the Ethereum
    side.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Harmony_multisig.sol
  - https://twitter.com/harmonyprotocol/status/1540110924400324608
  - https://twitter.com/1nf0s3cpt/status/1540139812715261952
  root_cause: Private key compromised
  tags:
    chains:
    - ETH
    exploits: null
    project:
    - Bridge
    vulnerabilities:
    - Private key compromised
networks:
  block_number: '15012670'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: 0.8.10
options: null
