info:
  description: On Jun-23-2022, A hacker stole $100 million from the bridge connecting Ethereum and harmonyprotocol. The hacker probably managed to get access to the 2 private keys that are part of the multisig which can calls unlock() on the Ethereum side.
  license: 'UNLICENSED'
  author: ['SunWeb3Sec', '0xDatapunk', 'finn79426']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Harmony_multisig.sol'
    - 'https://twitter.com/harmonyprotocol/status/1540110924400324608'
    - 'https://twitter.com/1nf0s3cpt/status/1540139812715261952'
  tags: 
    chains: ['ethereum']
    project: ['bridge']  
    vulnerabilities: ['private key compromised'] #wip: CWE here
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '15012670'
  is_forking: '1'
  private_key: ''
  solidity_version: '0.8.10'
interfaces:
address:
options: