address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - finn79426
  - SunWeb3Sec
  description: On Mar-29-2022, Auctus contract reported a critical vulnerability and
    was later exploited by hackers to profit about $720,000 from users who did not
    revoked the approvals.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Auctus_exp.sol
  - https://twitter.com/AuctusOptions/status/1508647849663291398?cxt=HHwWjICzpbzO5e8pAAAA
  - https://etherscan.io/tx/0x2e7d7e7a6eb157b98974c8687fbd848d0158d37edc1302ea08ee5ddb376befea
  tags:
    chains:
    - ethereum
    exploits:
    - abuse approval
    project:
    - token
    vulnerabilities: []
networks:
  block_number: '14460635'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: '>=0.7.0 <0.9.0'
options: null
