address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - finn79426
  - SunWeb3Sec
  description: On Mar-12-2022, the Paraluni was exploited, leading to the gain of
    ~$1.7M for the hacker. The hack is made possible due to a reentrancy bug (introduced
    by the use of a crafted token contract) in the depositByAddLiquidity() function,
    which somehow doubles the credits the hacker is able to claim.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Paraluni_exp.sol
  - https://halborn.com/explained-the-paraluni-hack-march-2022/
  - https://twitter.com/peckshield/status/1502815435498176514
  - https://mobile.twitter.com/paraluni/status/1502951606202994694
  - https://zhuanlan.zhihu.com/p/517535530
  - https://bscscan.com/tx/0x70f367b9420ac2654a5223cc311c7f9c361736a39fd4e7dff9ed1b85bab7ad54
  root_cause: Reentrancy & insufficient validation
  tags:
    chains:
    - BSC
    exploits:
    - Flashloan
    project:
    - DEX
    vulnerabilities:
    - Reentrancy
    - CWE-841
    - CWE-20
networks:
  block_number: '16008280'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: '>=0.7.0 <0.9.0'
options: null
