address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - zhouxianyuan
  description: On Nov-23-2022, $NUM of the numbersprotocol seems to be exploited with
    loss $13k due to the token is incompatible with the MultichainOrg Router. Specifically,
    $NUM does NOT implement the permit() function required by the Router; meanwhile,
    the token has a default fallback() which can be exploited.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/NUM_exp.sol
  - https://twitter.com/BlockSecTeam/status/1595346020237352960
  tags:
    chains:
    - ethereum
    exploits: []
    project:
    - token
    vulnerabilities:
    - incompatible
networks:
  block_number: '16029969'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: ^0.8.10
options: null
