address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - SunWeb3Sec
  - finn79426
  description: On Jun-06-2022, a flashloan attack happened on $Discover. The attacker
    used BSC-USD to redeem a large number of $Discover tokens repeatedly, making a
    profit of about 49 $BNB and transferred to Tornado.cash.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Discover_exp.sol
  - https://www.twitter.com/BeosinAlert/status/1533734518623899648
  - https://www.anquanke.com/post/id/274003
  - https://bscscan.com/tx/0x8a33a1f8c7af372a9c81ede9e442114f0aabb537e5c3a22c0fd7231c4820f1e9
  - https://bscscan.com/tx/0x1dd4989052f69cd388f4dfbeb1690a3f3a323ebb73df816e5ef2466dc98fa4a4
  tags:
    chains:
    - bsc
    exploits:
    - flashloan
    - price oracle manipulation
    project:
    - token
    - pledge
    vulnerabilities: []
networks:
  block_number: '18446845'
  is_forking: '1'
  node: bsc
  private_key: ''
  solidity_version: 0.8.10
options: null
