address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - finn79426
  description: On Oct-27-2022, @TeamFinance was exploited in https://etherscan.io/tx/0xb2e3ea72d353da43a2ac9a8f1670fd16463ab370e563b9b5b26119b2601277ce
    due to a flawed migrate() which lacks of check function parameter legitimate,
    leading to the loss of ~$15.8M for the protocol:$11.5M.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/TeamFinance.exp.sol
  - https://twitter.com/TeamFinance_/status/1585770918873542656
  - https://twitter.com/peckshield/status/1585587858978623491
  - https://twitter.com/solid_group_1/status/1585643249305518083
  - https://twitter.com/BeosinAlert/status/1585578499125178369
  root_cause: A flawed migrate() which lacks of check function parameter legitimate
  tags:
    chains:
    - ETH
    exploits: null
    project: null
    vulnerabilities:
    - CWE-20
networks:
  block_number: '15837893'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: ^0.8.10
options: null
