info:
  description: On Oct-14-2022, EFLeverVault contract was hit by a Flashloan attack that resulted in a cumulative profit of 480 Ether from the MEV Bot and 268 Ether from the hackers. 
  license: 'UNLICENSED'
  author: 'SunWeb3Sec'
  references:
    - 'url'
    - 'cve'
  tags: 
    chains: ['eth']
    project: ['vault']  
    vulnerabilities: [] #wip: CWE here
    exploits: ['flashloan']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '15746199'
  is_forking: '1'
  private_key: ''
  solidity_version: 0.8.10
interfaces:
address:
options: