info:
  description: 'On Sep-28-2022, an anonymous attacker noticed a flaw in the bots arbitrage contract code, and stole not only the recently acquired 800 ETH, but the entire 1,101 ETH in 0xbad’s wallet.'
  license: 
  author: ['eugenioclrc', 'kayaba2002']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/MEVbadc0de_exp.sol'
    - 'https://rekt.news/ripmevbot/'
    - 'https://etherscan.io/tx/0x59ddcf5ee5c687af2cbf291c3ac63bf28316a8ecbb621d9f62d07fa8a5b8ef4e'
  tags: ['ethereum', 'Badc0de']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '15625424'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
  url: ''
interfaces:
address:
  weth: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
  pool: '0x1E0447b19BB6EcFdAe1e4AE1694b0C3659614e4e'
  MEVBOT: '0xbaDc0dEfAfCF6d4239BDF0b66da4D7Bd36fCF05A'
options: