address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - finn79426
  description: On Sep-08-2022, NewFreeDao was hacked by flashloan attack and lost
    4,481 BNB (~125M US$).
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/NewFreeDAO_exp.sol
  - https://twitter.com/SlowMist_Team/status/1567854876633309186
  - https://bscscan.com/tx/0x1fea385acf7ff046d928d4041db017e1d7ead66727ce7aacb3296b9d485d4a26
  root_cause: Incorrect reward calculation
  tags:
    chains:
    - BSC
    exploits:
    - Flashloan
    - Price manipulation
    project:
    - ERC20
    - Reward
    vulnerabilities:
    - Business logic issue
    - CWE-682
networks:
  block_number: '21140434'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: ^0.8.10
options: null
