address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - finn79426
  - SunWeb3Sec
  description: null
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/CompoundTusd_exp.sol
  - https://blog.openzeppelin.com/compound-tusd-integration-issue-retrospective/
  - https://medium.com/chainsecurity/trueusd-compound-vulnerability-bc5b696d29e2
  root_cause: Multiple entry points
  tags:
    chains:
    - ETH
    exploits: null
    project:
    - Lending
    - DAO
    vulnerabilities: null
networks:
  block_number: '14266479'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: 0.8.10
options: null
