address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - finn79426
  - SunWeb3Sec
  description: On Mar-21-2022,
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/CompoundTusd_exp.sol
  - https://blog.openzeppelin.com/compound-tusd-integration-issue-retrospective/
  - https://medium.com/chainsecurity/trueusd-compound-vulnerability-bc5b696d29e2
  tags:
    chains:
    - ethereum
    exploits: []
    project:
    - token
    - lending
    - dao
    vulnerabilities:
    - multiple entry points
networks:
  block_number: '14266479'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: 0.8.10
options: null
