info:
  description: On Mar-21-2022, OneRing Finance was hacked via flashloan attack and the hacker managed to steal 1,454,672.244369 USDC ($1,454,672.24). 
  license: 'UNLICENSED'
  author: ['finn79426', 'SunWeb3Sec']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/OneRing_exp.sol'
    - 'https://medium.com/oneringfinance/onering-finance-exploit-post-mortem-after-oshare-hack-602a529db99b'
    - 'https://ftmscan.com/tx/0xca8dd33850e29cf138c8382e17a19e77d7331b57c7a8451648788bbb26a70145'
  tags: 
    chains: ['fantom']
    project: ['token']  #wip
    vulnerabilities: [] #wip: CWE here
    exploits: ['flashloan', 'price oracle manipulation']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '34041499'
  is_forking: '1'
  private_key: ''
  solidity_version: '0.8.10'
interfaces:
- Uniswap/IUniswapV2Pair.sol
address:
options: