address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - finn79426
  - SunWeb3Sec
  description: On Mar-21-2022, OneRing Finance was hacked via flashloan attack and
    the hacker managed to steal 1,454,672.244369 USDC ($1,454,672.24).
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/OneRing_exp.sol
  - https://medium.com/oneringfinance/onering-finance-exploit-post-mortem-after-oshare-hack-602a529db99b
  - https://ftmscan.com/tx/0xca8dd33850e29cf138c8382e17a19e77d7331b57c7a8451648788bbb26a70145
  root_cause: Incorrect price calculation via reverse
  tags:
    chains:
    - Fantom
    exploits:
    - Flashloan
    - Price manipulation
    project:
    - Yield
    vulnerabilities: 
    - CWE-682
    - Business logic issue
networks:
  block_number: '34041499'
  is_forking: '1'
  node: fantom
  private_key: null
  solidity_version: 0.8.10
options: null
