info:
  description: On Apr-22-2022, a hacker exploited a vulnerability in Zeed's protocols reward distribution system and drained over $1M In BSC-USD tokens. This attack is a flash loan attack launched by hackers using YEED's basic smart contract vulnerability.
  license: 'UNLICENSED'
  author: ['finn79426', 'SunWeb3Sec']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Zeed_exp.sol'
    - 'https://www.cryptotimes.io/hacker-leaves-1m-to-self-destruct-after-zeed-protocol-exploit/'
    - 'https://medium.com/@zeedcommunity/the-solution-for-the-yeed-lp-pool-attack-a120c53948cd'
    - 'https://bscscan.com/tx/0x0507476234193a9a5c7ae2c47e4c4b833a7c3923cefc6fd7667b72f3ca3fa83a'
  tags: 
    chains: ['bsc']
    project: ['token', 'lending'] #WIP  
    vulnerabilities: ['Reward distribution flaw'] #wip: CWE here
    exploits: ['flashloan']  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '17132514'
  is_forking: '1'
  private_key: ''
  solidity_version: '0.8.10'
interfaces:
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
- PancakeSwap/IPancakePair.sol
address:
options: