address: null
development_framework:
  framework: foundry
  script: null
info:
  author:
  - zzzuhaibmohd
  - SunWeb3Sec
  - finn79426
  description: On May-29-2022, a flashloan attack happened on $NOVO with loss 279
    BNB. The attacker borrowed 17.2 WBNB from flashloan, and  exchanged the NOVO with
    WBNB. The attacker then transferred a large amount of NOVO from the LP by using
    transferFrom without verification, causing the price of NOVO in the LP to increase,
    and finally the attacker exchanged the NOVO to WBNB at a high price to make a
    profit.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Novo_exp.sol
  - https://www.panewslab.com/zh_hk/articledetails/f40t9xb4.html
  - https://bscscan.com/tx/0xc346adf14e5082e6df5aeae650f3d7f606d7e08247c2b856510766b4dfcdc57f
  - https://bscscan.com/address/0xa0787daad6062349f63b7c228cbfd5d8a3db08f1#code
  root_cause: No sender address validation
  tags:
    chains:
    - BSC
    exploits:
    - Flashloan
    - Price manipulation
    project:
    - Deflationary token
    vulnerabilities:
    - CWE-20
networks:
  block_number: '18225002'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: ^0.8.10
options: null
