info:
  description: On Nov-15-2022, Sheep_Farm22 is attacked due to an incorrect implementation of register function and lost ~1BNB. Function register will check the user's timestamp to ensure it is a new user. However, it does not update the timestamp after the registration. In this case, the attacker can invoke the function register for multiple times. 
  license: 'UNLICENSED'
  author: ['zhouxianyuan']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/SheepFram_exp.sol'
    - 'https://twitter.com/AnciliaInc/status/1592658104394473472'
    - 'https://twitter.com/BlockSecTeam/status/1592734292727455744'
  tags: 
    chains: ['bsc']
    project: ['farming']  
    vulnerabilities: ['logic issue'] #wip: CWE here
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '23088156'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
address:
options: