address:
  pair: '0x02b0551B656509754285eeC81eE894338E14C5DD'
  router: '0x10ED43C718714eb63d5aA57B78B54704E256024E'
  vulnerableToken: '0xF40d33DE6737367A1cCB0cE6a056698D993A17E1'
  wbnb: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c'
development_framework:
  framework: hardhat
  script: null
info:
  author: unknown
  description: On Jan-17-2022 03:34:17 AM +UTC, an attacker manipulate the price of
    BURG in the PancakeSwap and gained ~77K worth of asset. The attack was caused
    by a smart contract vulnerability that allows the token to burn in any account.
  license: null
  references: null 
  root_cause: Public burn function
  tags:
    chains:
    - BSC
    exploits:
    - Flashloan
    - Price manipulation
    project:
    - ERC20
    vulnerabilities:
    - CWE-20
    - CWE-20
networks:
  block_number: '14433982'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: 0.8.4
options:
  burnAmount: 19999e18
  numberOfBurnOperations: '10'
  numberOfSwapOperations: '4'
  swapAmount: 19999e18
