address: null
development_framework:
  framework: foundry
  script: null
info:
  author: zhouxianyuan
  description: On Oct-17-2022, Uerii Token was hacked and lost $2.4 k due to the public
    mint function.
  license: UNLICENSED
  references:
  - https://twitter.com/peckshield/status/1581988895142526976
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Uerii_exp.sol
  root_cause: Incorrect access control
  tags:
    chains:
    - ETH
    exploits: null
    project:
    - ERC20
    vulnerabilities:
    - CWE-284
networks:
  block_number: '15767837'
  is_forking: '1'
  node: eth
  private_key: null
  solidity_version: 0.8.10
options: null
