address: null
development_framework:
  framework: foundry
  script: attack.ts
info:
  author:
  - finn79426
  description: On Aug-07-2022, EGD_Finance was attacked, and the loss is around 36,044
    USDT. This is a typical price manipulation attack.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/EGD-Finance.exp.sol
  - https://twitter.com/BlockSecTeam/status/1556483435388350464
  - https://twitter.com/PeckShieldAlert/status/1556486817406283776
  root_cause: Incorrect price calculation via balanceOf
  tags:
    chains:
    - BSC
    exploits:
    - Flashloan
    - Price manipulation
    project:
    - DEX
    vulnerabilities:
    - Business logic issue
    - CWE-682
networks:
  block_number: '20245539'
  is_forking: '1'
  node: bsc
  private_key: null
  solidity_version: ^0.8.10
options: null
