info:
  description: On Aug-07-2022, EGD_Finance was attacked, and the loss is around 36,044 USDT. This is a typical price manipulation attack.
  license: 'UNLICENSED'
  author: ['finn79426']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/EGD-Finance.exp.sol'
    - 'https://twitter.com/BlockSecTeam/status/1556483435388350464'
    - 'https://twitter.com/PeckShieldAlert/status/1556486817406283776'
  tags: 
    chains: ['bsc']
    project: ['token']  
    vulnerabilities: [] #wip: CWE here
    exploits: ['flashloan', 'price manipulation']  
development_framework:
  script: 'attack.ts'
  framework: 'foundry'
networks:
  block_number: '20245539'
  is_forking: '1'
  private_key: ''
  solidity_version: ^0.8.10
interfaces:
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
- PancakeSwap/IPancakePair.sol
address:
options: