address: null
development_framework:
  framework: foundry
  script: ''
info:
  author: zhouxianyuan
  description: On Oct-20-2022, HEALTH token (0x32b166e082993af6598a89397e82e123ca44e74e)
    on BSC has been attacked. The project is susceptible to price manipulation vulnerability.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/HEALTH_exp.sol
  - https://twitter.com/BlockSecTeam/status/1583073442433495040
  tags:
    chains:
    - bsc
    exploits:
    - price oracle manipulation
    project:
    - token
    vulnerabilities: []
networks:
  block_number: '22337425'
  is_forking: '1'
  node: bsc
  private_key: ''
  solidity_version: 0.8.10
options: null
