info:
  description: On Aug-01-2022, the Nomad bridge experienced an exploit causing a loss of around $190M worth of assets. The vulnerability was in the initialization process where the “committedRoot” is set as ZERO. Therefore, the attackers were able to bypass the message verification process and drain the tokens from the bridge contract.
  license: 'UNLICENSED'
  author: ['Cache-and-Burn']
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/NomadBridge.exp.sol'
    - 'https://twitter.com/samczsun/status/1554252024723546112'
    - 'https://www.certik.com/resources/blog/28fMavD63CpZJOKOjb9DX3-nomad-bridge-exploit-incident-analysis'
    - 'https://blog.coinbase.com/nomad-bridge-incident-analysis-899b425b0f34'
  tags: 
    chains: ['ethereum']
    project: ['token', 'staking']  
    vulnerabilities: ['logic issue'] #wip: CWE here
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '15259100'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.10'
interfaces:
address:
options: