info:
  description: On Jan-17-2022 03:34:17 AM +UTC, an attacker manipulate the price of BURG in the PancakeSwap and gained ~77K worth of asset. The attack was caused by a smart contract vulnerability that allows the token to burn in any account. 
  license: 
  author: 'unknown'
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/BNB48MEVBot_exp.sol'
    - 'https://blocksecteam.medium.com/the-two-sides-of-the-private-tx-service-on-binance-smart-chain-a76917c3ce51'
    - 'https://bscscan.com/tx/0xd48758ef48d113b78a09f7b8c7cd663ad79e9965852e872fdfc92234c3e598d2'
  tags: ['bsc']  
development_framework:
  script: 'attack.ts'
  framework: 'hardhat'
networks:
  block_number: '14433982'
  is_forking: '1'
  private_key: ''
  solidity_version: 0.8.4
  url: https://patient-dawn-thunder.bsc.discover.quiknode.pro/[PRIVATE_KEY]/
interfaces:
- PancakeSwap/IERC20.sol
- PancakeSwap/IPancakeRouter01.sol
- PancakeSwap/IPancakeRouter02.sol
- PancakeSwap/IPancakePair.sol
- PancakeSwap/IWETH.sol
address:
  pair: '0x02b0551B656509754285eeC81eE894338E14C5DD'
  router: '0x10ED43C718714eb63d5aA57B78B54704E256024E'
  vulnerableToken: '0xF40d33DE6737367A1cCB0cE6a056698D993A17E1'
  wbnb: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c'
options:
  burn_amount: '19999'
  number_of_burn_operations: '11'
  number_of_swap_operations: '4'
  swap_amount: '19999'