info:
  description: 'Until Oct-02-2022, the attack causes Transit Swap to lose $21 million due to the interal bug of incorrect owner address validation, which allows the hacker to perform transferFrom to frasfer amount of innocent user to the hacker.'
  license: 
  author: 'SunWeb3Sec'
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/TransitSwap_exp.sol'
    - 'https://twitter.com/TransitFinance/status/1576463550557483008'
    - 'https://bscscan.com/tx/0x181a7882aac0eab1036eedba25bc95a16e10f61b5df2e99d240a16c334b9b189'
  tags: ['bsc', 'transit swap'] 
development_framework:
  script: 
  framework: 'foundry'
networks:
  block_number: '21816545'
  is_forking: '1'
  private_key: ''
  solidity_version: '^0.8.13'
  url: 
interfaces:
address:
  TransitSwap: '0x8785bb8deAE13783b24D7aFE250d42eA7D7e9d72'
  busd: '0x55d398326f99059fF775485246999027B3197955'
options:
