address: null
development_framework:
  framework: foundry
  script: ''
info:
  author:
  - 0xDatapunk
  - SunWeb3Sec
  - lmanini
  - finn79426
  description: On Apr-17-2022, the BeanstalkFarms was exploited, leading to the gain
    of $80+M for the hacker (The protocol loss may be larger), including 24,830 ETH
    and 36M BEAN. The hack is made possible due to the flashloan-assisted (immediate)
    pass of BIP18. The BIP18 leads to the crafted code execution with the governance
    privilege to drain the pool fund.
  license: UNLICENSED
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Beanstalk_exp.sol
  - https://rekt.news/beanstalk-rekt/
  - https://medium.com/uno-re/beanstalk-farms-hacked-total-damage-is-182-million-b699dd3e5c8
  - https://twitter.com/peckshield/status/1515680335769456640
  - https://etherscan.io/tx/0x68cdec0ac76454c3b0f7af0b8a3895db00adf6daaf3b50a99716858c4fa54c6f
  - https://etherscan.io/tx/0xcd314668aaa9bbfebaf1a0bd2b6553d01dd58899c508d4729fa7311dc5d33ad7
  tags:
    chains:
    - ethereum
    exploits:
    - flashloan
    project:
    - token
    - lending
    - dao
    vulnerabilities: []
networks:
  block_number: '14595905'
  is_forking: '1'
  node: eth
  private_key: ''
  solidity_version: '>=0.7.0 <0.9.0'
options: null
