info:
  description: On Oct-11-2022, TempleDao was attacked and lost $2.3 million. The root cause is the insufficient access control to the migrateStake function. 
  license: 'UNLICENSED'
  author: 'SunWeb3Sec'
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Templedao_exp.sol'
    - 'https://twitter.com/BlockSecTeam/status/1579843881893769222'
    - 'https://etherscan.io/tx/0x8c3f442fc6d640a6ff3ea0b12be64f1d4609ea94edd2966f42c01cd9bdcf04b5'
  tags: 
    chains: ['eth']
    project: ['dao', 'staking']  
    vulnerabilities: ['access control', 'CWE284'] #wip: CWE here
    exploits: []
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '15725066'
  is_forking: '1'
  private_key: ''
  solidity_version: 0.8.10
interfaces:
address:
options: