address:
  BUSD: '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56'
  Bot: '0x64dD59D6C7f09dc05B472ce5CB961b6E10106E1d'
  USDC: '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d'
  USDT: '0x55d398326f99059fF775485246999027B3197955'
  WBNB: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c'
development_framework:
  framework: foundry
  script: ''
info:
  author: zhouxianyuan
  description: On Sep-13-2022 01:07:20 PM +UTC, the attacker abused the private tx
    service of BNB48 to hide its attack transaction (The attack profit is around $150K
    USD). (WIP)
  license: null
  references:
  - https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/MEVbadc0de_exp.sol
  - https://twitter.com/BlockSecTeam/status/1573252869322846209
  - https://bscscan.com/tx/0xd692f71de2768017390395db815d34033013136c378177c05d0d46ef3b6f0897
  tags:
    chains:
    - bsc
    exploits:
    - flashloan
    - price oracle manipulation
    project:
    - erc20
    vulnerabilities: []
networks:
  block_number: '21297409'
  is_forking: '1'
  node: bsc
  private_key: ''
  solidity_version: ^0.8.10
  url: ''
options: null
